// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// AwsSourceDetails message describes a specific source details for the
/// AWS source type.
public struct AwsSourceDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The AWS region that the source VMs will be migrated from.
  public var awsRegion: Swift.String = Swift.String()

  /// Output only. State of the source as determined by the health check.
  public var state: AwsSourceDetails.State = AwsSourceDetails.State()

  /// Output only. Provides details on the state of the Source in case of an
  /// error.
  public var error: GoogleRpc.Status? = nil

  /// AWS resource tags to limit the scope of the source inventory.
  public var inventoryTagList: [AwsSourceDetails.Tag] = []

  /// AWS security group names to limit the scope of the source
  /// inventory.
  public var inventorySecurityGroupNames: [Swift.String] = []

  /// User specified tags to add to every M2VM generated resource in AWS.
  /// These tags will be set in addition to the default tags that are set as part
  /// of the migration process. The tags must not begin with the reserved prefix
  /// `m2vm`.
  public var migrationResourcesUserTags: [Swift.String: Swift.String] = [:]

  /// Output only. The source's public IP. All communication initiated by this
  /// source will originate from this IP.
  public var publicIp: Swift.String = Swift.String()

  public var credentialsType: OneOf_CredentialsType? = nil

  /// Initialize a new instance of `AwsSourceDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsSourceDetails().with { $0.accessKeyCreds = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case accessKeyCreds = "accessKeyCreds"
    case awsRegion = "awsRegion"
    case state = "state"
    case error = "error"
    case inventoryTagList = "inventoryTagList"
    case inventorySecurityGroupNames = "inventorySecurityGroupNames"
    case migrationResourcesUserTags = "migrationResourcesUserTags"
    case publicIp = "publicIp"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.awsRegion = try container.decode(Swift.String.self, forKey: .awsRegion)
    self.state = try container.decode(AwsSourceDetails.State.self, forKey: .state)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    self.inventoryTagList = try container.decode(
      [AwsSourceDetails.Tag].self, forKey: .inventoryTagList)
    self.inventorySecurityGroupNames = try container.decode(
      [Swift.String].self, forKey: .inventorySecurityGroupNames)
    self.migrationResourcesUserTags = try container.decode(
      [Swift.String: Swift.String].self, forKey: .migrationResourcesUserTags)
    self.publicIp = try container.decode(Swift.String.self, forKey: .publicIp)

    var credentialsType: OneOf_CredentialsType? = nil
    let credentialsTypeCheckAndSet = {
      if credentialsType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'credentialsType'"))
      }
      credentialsType = $0
    }
    if let accessKeyCreds = try container.decodeIfPresent(
      AwsSourceDetails.AccessKeyCredentials?.self, forKey: .accessKeyCreds)
    {
      try credentialsTypeCheckAndSet(.accessKeyCreds(accessKeyCreds))
    }
    self.credentialsType = credentialsType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.awsRegion, forKey: .awsRegion)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.error, forKey: .error)
    try container.encode(self.inventoryTagList, forKey: .inventoryTagList)
    try container.encode(self.inventorySecurityGroupNames, forKey: .inventorySecurityGroupNames)
    try container.encode(self.migrationResourcesUserTags, forKey: .migrationResourcesUserTags)
    try container.encode(self.publicIp, forKey: .publicIp)

    if let choice = self.credentialsType {
      switch choice {
      case .accessKeyCreds(let value):
        try container.encode(value, forKey: .accessKeyCreds)
      }
    }
  }

  /// Message describing AWS Credentials using access key id and secret.
  public struct AccessKeyCredentials: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// AWS access key ID.
    public var accessKeyId: Swift.String = Swift.String()

    /// Input only. AWS secret access key.
    public var secretAccessKey: Swift.String = Swift.String()

    /// Input only. AWS session token.
    /// Used only when AWS security token service (STS) is responsible for
    /// creating the temporary credentials.
    public var sessionToken: Swift.String = Swift.String()

    /// Initialize a new instance of `AccessKeyCredentials`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AccessKeyCredentials().with { $0.accessKeyId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.AwsSourceDetails.AccessKeyCredentials"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Tag is an AWS tag representation.
  public struct Tag: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Key of tag.
    public var key: Swift.String = Swift.String()

    /// Required. Value of tag.
    public var value: Swift.String = Swift.String()

    /// Initialize a new instance of `Tag`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Tag().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.AwsSourceDetails.Tag"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The possible values of the state.
  public enum State: Codable, Equatable, Sendable {
    /// The state is unknown. This is used for API compatibility only and is not
    /// used by the system.
    case unspecified
    /// The state was not sampled by the health checks yet.
    case pending
    /// The source is available but might not be usable yet due to invalid
    /// credentials or another reason.
    /// The error message will contain further details.
    case failed
    /// The source exists and its credentials were verified.
    case active
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .failed: return 2
      case .active: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .failed: return "FAILED"
      case .active: return "ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "FAILED": self = .failed
      case "ACTIVE": self = .active
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .failed
      case 3: self = .active
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .failed: return try container.encode(2)
      case .active: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_CredentialsType: Codable, Equatable, Sendable {
    /// AWS Credentials using access key id and secret.
    indirect case accessKeyCreds(AwsSourceDetails.AccessKeyCredentials?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.AwsSourceDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
