// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// AwsVmDetails describes a VM in AWS.
public struct AwsVmDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The VM ID in AWS.
  public var vmId: Swift.String = Swift.String()

  /// The display name of the VM. Note that this value is not necessarily unique.
  public var displayName: Swift.String = Swift.String()

  /// The id of the AWS's source this VM is connected to.
  public var sourceId: Swift.String = Swift.String()

  /// The descriptive name of the AWS's source this VM is connected to.
  public var sourceDescription: Swift.String = Swift.String()

  /// Output only. The power state of the VM at the moment list was taken.
  public var powerState: AwsVmDetails.PowerState = AwsVmDetails.PowerState()

  /// The number of CPU cores the VM has.
  public var cpuCount: Swift.Int32 = Swift.Int32()

  /// The memory size of the VM in MB.
  public var memoryMb: Swift.Int32 = Swift.Int32()

  /// The number of disks the VM has.
  public var diskCount: Swift.Int32 = Swift.Int32()

  /// The total size of the storage allocated to the VM in MB.
  public var committedStorageMb: Swift.Int64 = Swift.Int64()

  /// The VM's OS.
  public var osDescription: Swift.String = Swift.String()

  /// The VM Boot Option.
  public var bootOption: AwsVmDetails.BootOption = AwsVmDetails.BootOption()

  /// The instance type of the VM.
  public var instanceType: Swift.String = Swift.String()

  /// The VPC ID the VM belongs to.
  public var vpcId: Swift.String = Swift.String()

  /// The security groups the VM belongs to.
  public var securityGroups: [AwsSecurityGroup] = []

  /// The tags of the VM.
  public var tags: [Swift.String: Swift.String] = [:]

  /// The AWS zone of the VM.
  public var zone: Swift.String = Swift.String()

  /// The virtualization type.
  public var virtualizationType: AwsVmDetails.VmVirtualizationType =
    AwsVmDetails.VmVirtualizationType()

  /// The CPU architecture.
  public var architecture: AwsVmDetails.VmArchitecture = AwsVmDetails.VmArchitecture()

  /// The number of vCPUs the VM has. It is calculated as the
  /// number of CPU cores * threads per CPU the VM has.
  public var vcpuCount: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `AwsVmDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsVmDetails().with { $0.vmId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible values for the power state of the VM.
  public enum PowerState: Codable, Equatable, Sendable {
    /// Power state is not specified.
    case unspecified
    /// The VM is turned on.
    case on
    /// The VM is turned off.
    case off
    /// The VM is suspended. This is similar to hibernation or sleep
    /// mode.
    case suspended
    /// The VM is starting.
    case pending
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .on: return 1
      case .off: return 2
      case .suspended: return 3
      case .pending: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "POWER_STATE_UNSPECIFIED"
      case .on: return "ON"
      case .off: return "OFF"
      case .suspended: return "SUSPENDED"
      case .pending: return "PENDING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PowerState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "POWER_STATE_UNSPECIFIED": self = .unspecified
      case "ON": self = .on
      case "OFF": self = .off
      case "SUSPENDED": self = .suspended
      case "PENDING": self = .pending
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PowerState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .on
      case 2: self = .off
      case 3: self = .suspended
      case 4: self = .pending
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .on: return try container.encode(1)
      case .off: return try container.encode(2)
      case .suspended: return try container.encode(3)
      case .pending: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible values for the vm boot option.
  public enum BootOption: Codable, Equatable, Sendable {
    /// The boot option is unknown.
    case unspecified
    /// The boot option is UEFI.
    case efi
    /// The boot option is LEGACY-BIOS.
    case bios
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .efi: return 1
      case .bios: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BOOT_OPTION_UNSPECIFIED"
      case .efi: return "EFI"
      case .bios: return "BIOS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BootOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BOOT_OPTION_UNSPECIFIED": self = .unspecified
      case "EFI": self = .efi
      case "BIOS": self = .bios
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BootOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .efi
      case 2: self = .bios
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .efi: return try container.encode(1)
      case .bios: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible values for the virtualization types of the VM.
  public enum VmVirtualizationType: Codable, Equatable, Sendable {
    /// The virtualization type is unknown.
    case unspecified
    /// The virtualziation type is HVM.
    case hvm
    /// The virtualziation type is PARAVIRTUAL.
    case paravirtual
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .hvm: return 1
      case .paravirtual: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VM_VIRTUALIZATION_TYPE_UNSPECIFIED"
      case .hvm: return "HVM"
      case .paravirtual: return "PARAVIRTUAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VmVirtualizationType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VM_VIRTUALIZATION_TYPE_UNSPECIFIED": self = .unspecified
      case "HVM": self = .hvm
      case "PARAVIRTUAL": self = .paravirtual
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VmVirtualizationType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .hvm
      case 2: self = .paravirtual
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .hvm: return try container.encode(1)
      case .paravirtual: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible values for the architectures of the VM.
  public enum VmArchitecture: Codable, Equatable, Sendable {
    /// The architecture is unknown.
    case unspecified
    /// The architecture is I386.
    case i386
    /// The architecture is X86_64.
    case x8664
    /// The architecture is ARM64.
    case arm64
    /// The architecture is X86_64_MAC.
    case x8664Mac
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .i386: return 1
      case .x8664: return 2
      case .arm64: return 3
      case .x8664Mac: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VM_ARCHITECTURE_UNSPECIFIED"
      case .i386: return "I386"
      case .x8664: return "X86_64"
      case .arm64: return "ARM64"
      case .x8664Mac: return "X86_64_MAC"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VmArchitecture/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VM_ARCHITECTURE_UNSPECIFIED": self = .unspecified
      case "I386": self = .i386
      case "X86_64": self = .x8664
      case "ARM64": self = .arm64
      case "X86_64_MAC": self = .x8664Mac
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VmArchitecture/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .i386
      case 2: self = .x8664
      case 3: self = .arm64
      case 4: self = .x8664Mac
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .i386: return try container.encode(1)
      case .x8664: return try container.encode(2)
      case .arm64: return try container.encode(3)
      case .x8664Mac: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.AwsVmDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
