// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AzureVmDetails describes a VM in Azure.
public struct AzureVmDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The VM full path in Azure.
  public var vmId: Swift.String = Swift.String()

  /// The power state of the VM at the moment list was taken.
  public var powerState: AzureVmDetails.PowerState = AzureVmDetails.PowerState()

  /// VM size as configured in Azure. Determines the VM's hardware spec.
  public var vmSize: Swift.String = Swift.String()

  /// The number of cpus the VM has.
  public var cpuCount: Swift.Int32 = Swift.Int32()

  /// The memory size of the VM in MB.
  public var memoryMb: Swift.Int32 = Swift.Int32()

  /// The number of disks the VM has, including OS disk.
  public var diskCount: Swift.Int32 = Swift.Int32()

  /// The total size of the storage allocated to the VM in MB.
  public var committedStorageMb: Swift.Int64 = Swift.Int64()

  /// Description of the OS disk.
  public var osDisk: AzureVmDetails.OSDisk? = nil

  /// Description of the data disks.
  public var disks: [AzureVmDetails.Disk] = []

  /// Description of the OS.
  public var osDescription: AzureVmDetails.OSDescription? = nil

  /// The VM Boot Option.
  public var bootOption: AzureVmDetails.BootOption = AzureVmDetails.BootOption()

  /// The tags of the VM.
  public var tags: [Swift.String: Swift.String] = [:]

  /// The VM's ComputerName.
  public var computerName: Swift.String = Swift.String()

  /// The CPU architecture.
  public var architecture: AzureVmDetails.VmArchitecture = AzureVmDetails.VmArchitecture()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AzureVmDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureVmDetails().with { $0.vmId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vmId = CodingKeys(stringValue: "vmId")
    static let powerState = CodingKeys(stringValue: "powerState")
    static let vmSize = CodingKeys(stringValue: "vmSize")
    static let cpuCount = CodingKeys(stringValue: "cpuCount")
    static let memoryMb = CodingKeys(stringValue: "memoryMb")
    static let diskCount = CodingKeys(stringValue: "diskCount")
    static let committedStorageMb = CodingKeys(stringValue: "committedStorageMb")
    static let osDisk = CodingKeys(stringValue: "osDisk")
    static let disks = CodingKeys(stringValue: "disks")
    static let osDescription = CodingKeys(stringValue: "osDescription")
    static let bootOption = CodingKeys(stringValue: "bootOption")
    static let tags = CodingKeys(stringValue: "tags")
    static let computerName = CodingKeys(stringValue: "computerName")
    static let architecture = CodingKeys(stringValue: "architecture")

    static let _knownKeys: Set<Swift.String> = [
      "vmId",
      "powerState",
      "vmSize",
      "cpuCount",
      "memoryMb",
      "diskCount",
      "committedStorageMb",
      "osDisk",
      "disks",
      "osDescription",
      "bootOption",
      "tags",
      "computerName",
      "architecture",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmId) {
      self.vmId = value
    }
    if let value = try container.decodeIfPresent(
      AzureVmDetails.PowerState.self, forKey: .powerState)
    {
      self.powerState = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmSize) {
      self.vmSize = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .cpuCount) {
      self.cpuCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .memoryMb) {
      self.memoryMb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .diskCount) {
      self.diskCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .committedStorageMb) {
      self.committedStorageMb = value
    }
    self.osDisk = try container.decodeIfPresent(AzureVmDetails.OSDisk.self, forKey: .osDisk)
    if let value = try container.decodeIfPresent([AzureVmDetails.Disk].self, forKey: .disks) {
      self.disks = value
    }
    self.osDescription = try container.decodeIfPresent(
      AzureVmDetails.OSDescription.self, forKey: .osDescription)
    if let value = try container.decodeIfPresent(
      AzureVmDetails.BootOption.self, forKey: .bootOption)
    {
      self.bootOption = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .computerName) {
      self.computerName = value
    }
    if let value = try container.decodeIfPresent(
      AzureVmDetails.VmArchitecture.self, forKey: .architecture)
    {
      self.architecture = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.vmId, forKey: .vmId)
    try container.encode(self.powerState, forKey: .powerState)
    try container.encode(self.vmSize, forKey: .vmSize)
    try container.encode(self.cpuCount, forKey: .cpuCount)
    try container.encode(self.memoryMb, forKey: .memoryMb)
    try container.encode(self.diskCount, forKey: .diskCount)
    try container.encode(self.committedStorageMb, forKey: .committedStorageMb)
    try container.encodeIfPresent(self.osDisk, forKey: .osDisk)
    try container.encode(self.disks, forKey: .disks)
    try container.encodeIfPresent(self.osDescription, forKey: .osDescription)
    try container.encode(self.bootOption, forKey: .bootOption)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.computerName, forKey: .computerName)
    try container.encode(self.architecture, forKey: .architecture)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A message describing the OS disk.
  public struct OSDisk: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The disk's type.
    public var type: Swift.String = Swift.String()

    /// The disk's full name.
    public var name: Swift.String = Swift.String()

    /// The disk's size in GB.
    public var sizeGb: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OSDisk`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OSDisk().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let type = CodingKeys(stringValue: "type")
      static let name = CodingKeys(stringValue: "name")
      static let sizeGb = CodingKeys(stringValue: "sizeGb")

      static let _knownKeys: Set<Swift.String> = [
        "type",
        "name",
        "sizeGb",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .sizeGb) {
        self.sizeGb = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.sizeGb, forKey: .sizeGb)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.AzureVmDetails.OSDisk"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A message describing a data disk.
  public struct Disk: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The disk name.
    public var name: Swift.String = Swift.String()

    /// The disk size in GB.
    public var sizeGb: Swift.Int32 = Swift.Int32()

    /// The disk's Logical Unit Number (LUN).
    public var lun: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Disk`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Disk().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let sizeGb = CodingKeys(stringValue: "sizeGb")
      static let lun = CodingKeys(stringValue: "lun")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "sizeGb",
        "lun",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .sizeGb) {
        self.sizeGb = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .lun) {
        self.lun = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.sizeGb, forKey: .sizeGb)
      try container.encode(self.lun, forKey: .lun)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.AzureVmDetails.Disk"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A message describing the VM's OS. Including OS, Publisher, Offer and Plan
  /// if applicable.
  public struct OSDescription: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// OS type.
    public var type: Swift.String = Swift.String()

    /// OS publisher.
    public var publisher: Swift.String = Swift.String()

    /// OS offer.
    public var offer: Swift.String = Swift.String()

    /// OS plan.
    public var plan: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OSDescription`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OSDescription().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let type = CodingKeys(stringValue: "type")
      static let publisher = CodingKeys(stringValue: "publisher")
      static let offer = CodingKeys(stringValue: "offer")
      static let plan = CodingKeys(stringValue: "plan")

      static let _knownKeys: Set<Swift.String> = [
        "type",
        "publisher",
        "offer",
        "plan",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .publisher) {
        self.publisher = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .offer) {
        self.offer = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .plan) {
        self.plan = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.publisher, forKey: .publisher)
      try container.encode(self.offer, forKey: .offer)
      try container.encode(self.plan, forKey: .plan)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.AzureVmDetails.OSDescription"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible values for the power state of the VM.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum PowerState: Codable, Equatable, Hashable, Sendable {
    /// Power state is not specified.
    case unspecified
    /// The VM is starting.
    case starting
    /// The VM is running.
    case running
    /// The VM is stopping.
    case stopping
    /// The VM is stopped.
    case stopped
    /// The VM is deallocating.
    case deallocating
    /// The VM is deallocated.
    case deallocated
    /// The VM's power state is unknown.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .starting: return 1
      case .running: return 2
      case .stopping: return 3
      case .stopped: return 4
      case .deallocating: return 5
      case .deallocated: return 6
      case .unknown: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "POWER_STATE_UNSPECIFIED"
      case .starting: return "STARTING"
      case .running: return "RUNNING"
      case .stopping: return "STOPPING"
      case .stopped: return "STOPPED"
      case .deallocating: return "DEALLOCATING"
      case .deallocated: return "DEALLOCATED"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PowerState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "POWER_STATE_UNSPECIFIED": self = .unspecified
      case "STARTING": self = .starting
      case "RUNNING": self = .running
      case "STOPPING": self = .stopping
      case "STOPPED": self = .stopped
      case "DEALLOCATING": self = .deallocating
      case "DEALLOCATED": self = .deallocated
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PowerState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .starting
      case 2: self = .running
      case 3: self = .stopping
      case 4: self = .stopped
      case 5: self = .deallocating
      case 6: self = .deallocated
      case 7: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("POWER_STATE_UNSPECIFIED")
      case .starting: return try container.encode("STARTING")
      case .running: return try container.encode("RUNNING")
      case .stopping: return try container.encode("STOPPING")
      case .stopped: return try container.encode("STOPPED")
      case .deallocating: return try container.encode("DEALLOCATING")
      case .deallocated: return try container.encode("DEALLOCATED")
      case .unknown: return try container.encode("UNKNOWN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible values for the vm boot option.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum BootOption: Codable, Equatable, Hashable, Sendable {
    /// The boot option is unknown.
    case unspecified
    /// The boot option is UEFI.
    case efi
    /// The boot option is BIOS.
    case bios
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .efi: return 1
      case .bios: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BOOT_OPTION_UNSPECIFIED"
      case .efi: return "EFI"
      case .bios: return "BIOS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BootOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BOOT_OPTION_UNSPECIFIED": self = .unspecified
      case "EFI": self = .efi
      case "BIOS": self = .bios
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BootOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .efi
      case 2: self = .bios
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("BOOT_OPTION_UNSPECIFIED")
      case .efi: return try container.encode("EFI")
      case .bios: return try container.encode("BIOS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible values for the VM architecture.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum VmArchitecture: Codable, Equatable, Hashable, Sendable {
    /// The architecture is unknown.
    case unspecified
    /// The architecture is one of the x86 architectures.
    case x86Family
    /// The architecture is ARM64.
    case arm64
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .x86Family: return 1
      case .arm64: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VM_ARCHITECTURE_UNSPECIFIED"
      case .x86Family: return "VM_ARCHITECTURE_X86_FAMILY"
      case .arm64: return "VM_ARCHITECTURE_ARM64"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VmArchitecture/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VM_ARCHITECTURE_UNSPECIFIED": self = .unspecified
      case "VM_ARCHITECTURE_X86_FAMILY": self = .x86Family
      case "VM_ARCHITECTURE_ARM64": self = .arm64
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VmArchitecture/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .x86Family
      case 2: self = .arm64
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("VM_ARCHITECTURE_UNSPECIFIED")
      case .x86Family: return try container.encode("VM_ARCHITECTURE_X86_FAMILY")
      case .arm64: return try container.encode("VM_ARCHITECTURE_ARM64")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.AzureVmDetails"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
