// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// AzureSourceDetails message describes a specific source details for the
/// Azure source type.
public struct AzureSourceDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. Azure subscription ID.
  public var subscriptionId: Swift.String = Swift.String()

  /// Immutable. The Azure location (region) that the source VMs will be migrated
  /// from.
  public var azureLocation: Swift.String = Swift.String()

  /// Output only. State of the source as determined by the health check.
  public var state: AzureSourceDetails.State = AzureSourceDetails.State()

  /// Output only. Provides details on the state of the Source in case of an
  /// error.
  public var error: GoogleRpc.Status? = nil

  /// User specified tags to add to every M2VM generated resource in Azure.
  /// These tags will be set in addition to the default tags that are set as part
  /// of the migration process. The tags must not begin with the reserved prefix
  /// `m4ce` or `m2vm`.
  public var migrationResourcesUserTags: [Swift.String: Swift.String] = [:]

  /// Output only. The ID of the Azure resource group that contains all resources
  /// related to the migration process of this source.
  public var resourceGroupId: Swift.String = Swift.String()

  public var credentialsType: OneOf_CredentialsType? = nil

  /// Initialize a new instance of `AzureSourceDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureSourceDetails().with { $0.clientSecretCreds = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case clientSecretCreds = "clientSecretCreds"
    case subscriptionId = "subscriptionId"
    case azureLocation = "azureLocation"
    case state = "state"
    case error = "error"
    case migrationResourcesUserTags = "migrationResourcesUserTags"
    case resourceGroupId = "resourceGroupId"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.subscriptionId = try container.decode(Swift.String.self, forKey: .subscriptionId)
    self.azureLocation = try container.decode(Swift.String.self, forKey: .azureLocation)
    self.state = try container.decode(AzureSourceDetails.State.self, forKey: .state)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    self.migrationResourcesUserTags = try container.decode(
      [Swift.String: Swift.String].self, forKey: .migrationResourcesUserTags)
    self.resourceGroupId = try container.decode(Swift.String.self, forKey: .resourceGroupId)

    var credentialsType: OneOf_CredentialsType? = nil
    let credentialsTypeCheckAndSet = {
      if credentialsType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'credentialsType'"))
      }
      credentialsType = $0
    }
    if let clientSecretCreds = try container.decodeIfPresent(
      AzureSourceDetails.ClientSecretCredentials?.self, forKey: .clientSecretCreds)
    {
      try credentialsTypeCheckAndSet(.clientSecretCreds(clientSecretCreds))
    }
    self.credentialsType = credentialsType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.subscriptionId, forKey: .subscriptionId)
    try container.encode(self.azureLocation, forKey: .azureLocation)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.error, forKey: .error)
    try container.encode(self.migrationResourcesUserTags, forKey: .migrationResourcesUserTags)
    try container.encode(self.resourceGroupId, forKey: .resourceGroupId)

    if let choice = self.credentialsType {
      switch choice {
      case .clientSecretCreds(let value):
        try container.encode(value, forKey: .clientSecretCreds)
      }
    }
  }

  /// Message describing Azure Credentials using tenant ID, client ID and secret.
  public struct ClientSecretCredentials: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Azure tenant ID.
    public var tenantId: Swift.String = Swift.String()

    /// Azure client ID.
    public var clientId: Swift.String = Swift.String()

    /// Input only. Azure client secret.
    public var clientSecret: Swift.String = Swift.String()

    /// Initialize a new instance of `ClientSecretCredentials`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClientSecretCredentials().with { $0.tenantId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.vmmigration.v1.AzureSourceDetails.ClientSecretCredentials"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The possible values of the state.
  public enum State: Codable, Equatable, Sendable {
    /// The state is unknown. This is used for API compatibility only and is not
    /// used by the system.
    case unspecified
    /// The state was not sampled by the health checks yet.
    case pending
    /// The source is available but might not be usable yet due to invalid
    /// credentials or another reason.
    /// The error message will contain further details.
    case failed
    /// The source exists and its credentials were verified.
    case active
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .failed: return 2
      case .active: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .failed: return "FAILED"
      case .active: return "ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "FAILED": self = .failed
      case "ACTIVE": self = .active
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .failed
      case 3: self = .active
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .failed: return try container.encode(2)
      case .active: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_CredentialsType: Codable, Equatable, Sendable {
    /// Azure Credentials using tenant ID, client ID and secret.
    indirect case clientSecretCreds(AzureSourceDetails.ClientSecretCredentials?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.AzureSourceDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
