// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// AzureVmDetails describes a VM in Azure.
public struct AzureVmDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The VM full path in Azure.
  public var vmId: Swift.String = Swift.String()

  /// The power state of the VM at the moment list was taken.
  public var powerState: AzureVmDetails.PowerState = AzureVmDetails.PowerState()

  /// VM size as configured in Azure. Determines the VM's hardware spec.
  public var vmSize: Swift.String = Swift.String()

  /// The number of cpus the VM has.
  public var cpuCount: Swift.Int32 = Swift.Int32()

  /// The memory size of the VM in MB.
  public var memoryMb: Swift.Int32 = Swift.Int32()

  /// The number of disks the VM has, including OS disk.
  public var diskCount: Swift.Int32 = Swift.Int32()

  /// The total size of the storage allocated to the VM in MB.
  public var committedStorageMb: Swift.Int64 = Swift.Int64()

  /// Description of the OS disk.
  public var osDisk: AzureVmDetails.OSDisk? = nil

  /// Description of the data disks.
  public var disks: [AzureVmDetails.Disk] = []

  /// Description of the OS.
  public var osDescription: AzureVmDetails.OSDescription? = nil

  /// The VM Boot Option.
  public var bootOption: AzureVmDetails.BootOption = AzureVmDetails.BootOption()

  /// The tags of the VM.
  public var tags: [Swift.String: Swift.String] = [:]

  /// The VM's ComputerName.
  public var computerName: Swift.String = Swift.String()

  /// The CPU architecture.
  public var architecture: AzureVmDetails.VmArchitecture = AzureVmDetails.VmArchitecture()

  /// Initialize a new instance of `AzureVmDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureVmDetails().with { $0.vmId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A message describing the OS disk.
  public struct OSDisk: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The disk's type.
    public var type: Swift.String = Swift.String()

    /// The disk's full name.
    public var name: Swift.String = Swift.String()

    /// The disk's size in GB.
    public var sizeGb: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `OSDisk`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OSDisk().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.AzureVmDetails.OSDisk"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A message describing a data disk.
  public struct Disk: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The disk name.
    public var name: Swift.String = Swift.String()

    /// The disk size in GB.
    public var sizeGb: Swift.Int32 = Swift.Int32()

    /// The disk's Logical Unit Number (LUN).
    public var lun: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Disk`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Disk().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.AzureVmDetails.Disk"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A message describing the VM's OS. Including OS, Publisher, Offer and Plan
  /// if applicable.
  public struct OSDescription: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// OS type.
    public var type: Swift.String = Swift.String()

    /// OS publisher.
    public var publisher: Swift.String = Swift.String()

    /// OS offer.
    public var offer: Swift.String = Swift.String()

    /// OS plan.
    public var plan: Swift.String = Swift.String()

    /// Initialize a new instance of `OSDescription`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OSDescription().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.AzureVmDetails.OSDescription"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Possible values for the power state of the VM.
  public enum PowerState: Codable, Equatable, Sendable {
    /// Power state is not specified.
    case unspecified
    /// The VM is starting.
    case starting
    /// The VM is running.
    case running
    /// The VM is stopping.
    case stopping
    /// The VM is stopped.
    case stopped
    /// The VM is deallocating.
    case deallocating
    /// The VM is deallocated.
    case deallocated
    /// The VM's power state is unknown.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .starting: return 1
      case .running: return 2
      case .stopping: return 3
      case .stopped: return 4
      case .deallocating: return 5
      case .deallocated: return 6
      case .unknown: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "POWER_STATE_UNSPECIFIED"
      case .starting: return "STARTING"
      case .running: return "RUNNING"
      case .stopping: return "STOPPING"
      case .stopped: return "STOPPED"
      case .deallocating: return "DEALLOCATING"
      case .deallocated: return "DEALLOCATED"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PowerState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "POWER_STATE_UNSPECIFIED": self = .unspecified
      case "STARTING": self = .starting
      case "RUNNING": self = .running
      case "STOPPING": self = .stopping
      case "STOPPED": self = .stopped
      case "DEALLOCATING": self = .deallocating
      case "DEALLOCATED": self = .deallocated
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PowerState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .starting
      case 2: self = .running
      case 3: self = .stopping
      case 4: self = .stopped
      case 5: self = .deallocating
      case 6: self = .deallocated
      case 7: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .starting: return try container.encode(1)
      case .running: return try container.encode(2)
      case .stopping: return try container.encode(3)
      case .stopped: return try container.encode(4)
      case .deallocating: return try container.encode(5)
      case .deallocated: return try container.encode(6)
      case .unknown: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible values for the vm boot option.
  public enum BootOption: Codable, Equatable, Sendable {
    /// The boot option is unknown.
    case unspecified
    /// The boot option is UEFI.
    case efi
    /// The boot option is BIOS.
    case bios
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .efi: return 1
      case .bios: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BOOT_OPTION_UNSPECIFIED"
      case .efi: return "EFI"
      case .bios: return "BIOS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BootOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BOOT_OPTION_UNSPECIFIED": self = .unspecified
      case "EFI": self = .efi
      case "BIOS": self = .bios
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BootOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .efi
      case 2: self = .bios
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .efi: return try container.encode(1)
      case .bios: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible values for the VM architecture.
  public enum VmArchitecture: Codable, Equatable, Sendable {
    /// The architecture is unknown.
    case unspecified
    /// The architecture is one of the x86 architectures.
    case x86Family
    /// The architecture is ARM64.
    case arm64
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .x86Family: return 1
      case .arm64: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VM_ARCHITECTURE_UNSPECIFIED"
      case .x86Family: return "VM_ARCHITECTURE_X86_FAMILY"
      case .arm64: return "VM_ARCHITECTURE_ARM64"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VmArchitecture/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VM_ARCHITECTURE_UNSPECIFIED": self = .unspecified
      case "VM_ARCHITECTURE_X86_FAMILY": self = .x86Family
      case "VM_ARCHITECTURE_ARM64": self = .arm64
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VmArchitecture/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .x86Family
      case 2: self = .arm64
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .x86Family: return try container.encode(1)
      case .arm64: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.AzureVmDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
