// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// BootDiskDefaults hold information about the boot disk of a VM.
public struct BootDiskDefaults: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The name of the disk.
  public var diskName: Swift.String = Swift.String()

  /// Optional. The type of disk provisioning to use for the VM.
  public var diskType: ComputeEngineDiskType = ComputeEngineDiskType()

  /// Optional. Specifies a unique device name of your choice that is reflected
  /// into the /dev/disk/by-id/google-* tree of a Linux operating system running
  /// within the instance. If not specified, the server chooses a default device
  /// name to apply to this disk, in the form persistent-disk-x, where x is a
  /// number assigned by Google Compute Engine. This field is only applicable for
  /// persistent disks.
  public var deviceName: Swift.String = Swift.String()

  /// Optional. The encryption to apply to the boot disk.
  public var encryption: Encryption? = nil

  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BootDiskDefaults`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BootDiskDefaults().with { $0.image = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let image = CodingKeys(stringValue: "image")
    static let diskName = CodingKeys(stringValue: "diskName")
    static let diskType = CodingKeys(stringValue: "diskType")
    static let deviceName = CodingKeys(stringValue: "deviceName")
    static let encryption = CodingKeys(stringValue: "encryption")

    static let _knownKeys: Set<Swift.String> = [
      "image",
      "diskName",
      "diskType",
      "deviceName",
      "encryption",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .diskName) {
      self.diskName = value
    }
    if let value = try container.decodeIfPresent(ComputeEngineDiskType.self, forKey: .diskType) {
      self.diskType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deviceName) {
      self.deviceName = value
    }
    self.encryption = try container.decodeIfPresent(Encryption.self, forKey: .encryption)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let image = try container.decodeIfPresent(
      BootDiskDefaults.DiskImageDefaults?.self, forKey: .image)
    {
      try sourceCheckAndSet(.image(image))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.diskName, forKey: .diskName)
    try container.encode(self.diskType, forKey: .diskType)
    try container.encode(self.deviceName, forKey: .deviceName)
    try container.encodeIfPresent(self.encryption, forKey: .encryption)

    if let choice = self.source {
      switch choice {
      case .image(let value):
        try container.encode(value, forKey: .image)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Contains details about the image source used to create the disk.
  public struct DiskImageDefaults: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The Image resource used when creating the disk.
    public var sourceImage: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `DiskImageDefaults`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DiskImageDefaults().with { $0.sourceImage = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sourceImage = CodingKeys(stringValue: "sourceImage")

      static let _knownKeys: Set<Swift.String> = [
        "sourceImage"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceImage) {
        self.sourceImage = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sourceImage, forKey: .sourceImage)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vmmigration.v1.BootDiskDefaults.DiskImageDefaults"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// The image to use when creating the disk.
    indirect case image(BootDiskDefaults.DiskImageDefaults?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.BootDiskDefaults"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
