// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Compute Engine disk target details.
public struct ComputeEngineDisk: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Target Compute Engine Disk ID.
  /// This is the resource ID segment of the Compute Engine Disk to create.
  /// In the resource name compute/v1/projects/{project}/zones/{zone}/disks/disk1
  /// "disk1" is the resource ID for the disk.
  public var diskId: Swift.String = Swift.String()

  /// Required. The Compute Engine zone in which to create the disk. Should be of
  /// the form: projects/{target-project}/locations/{zone}
  public var zone: Swift.String = Swift.String()

  /// Optional. Replication zones of the regional disk. Should be of the form:
  /// projects/{target-project}/locations/{replica-zone}
  /// Currently only one replica zone is supported.
  public var replicaZones: [Swift.String] = []

  /// Required. The disk type to use.
  public var diskType: ComputeEngineDiskType = ComputeEngineDiskType()

  /// Initialize a new instance of `ComputeEngineDisk`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeEngineDisk().with { $0.diskId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ComputeEngineDisk"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
