// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// ComputeEngineDisksTargetDetails is a collection of created Persistent Disks
/// details.
public struct ComputeEngineDisksTargetDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The details of each created Persistent Disk.
  public var disks: [PersistentDisk] = []

  /// Details of the VM the disks are attached to.
  public var vmTarget: OneOf_VmTarget? = nil

  /// Initialize a new instance of `ComputeEngineDisksTargetDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeEngineDisksTargetDetails().with { $0.disksTargetDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case disksTargetDetails = "disksTargetDetails"
    case vmTargetDetails = "vmTargetDetails"
    case disks = "disks"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.disks = try container.decode([PersistentDisk].self, forKey: .disks)

    var vmTarget: OneOf_VmTarget? = nil
    let vmTargetCheckAndSet = {
      if vmTarget != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'vmTarget'"))
      }
      vmTarget = $0
    }
    if let disksTargetDetails = try container.decodeIfPresent(
      DisksMigrationDisksTargetDetails?.self, forKey: .disksTargetDetails)
    {
      try vmTargetCheckAndSet(.disksTargetDetails(disksTargetDetails))
    }
    if let vmTargetDetails = try container.decodeIfPresent(
      DisksMigrationVmTargetDetails?.self, forKey: .vmTargetDetails)
    {
      try vmTargetCheckAndSet(.vmTargetDetails(vmTargetDetails))
    }
    self.vmTarget = vmTarget
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.disks, forKey: .disks)

    if let choice = self.vmTarget {
      switch choice {
      case .disksTargetDetails(let value):
        try container.encode(value, forKey: .disksTargetDetails)
      case .vmTargetDetails(let value):
        try container.encode(value, forKey: .vmTargetDetails)
      }
    }
  }

  /// Details of the VM the disks are attached to.
  public enum OneOf_VmTarget: Codable, Equatable, Sendable {
    /// Details of the disks-only migration target.
    indirect case disksTargetDetails(DisksMigrationDisksTargetDetails?)
    /// Details for the VM the migrated data disks are attached to.
    indirect case vmTargetDetails(DisksMigrationVmTargetDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ComputeEngineDisksTargetDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
