// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ComputeEngineTargetDetails is a collection of details for creating a VM in a
/// target Compute Engine project.
public struct ComputeEngineTargetDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the VM to create.
  public var vmName: Swift.String = Swift.String()

  /// The Google Cloud target project ID or project name.
  public var project: Swift.String = Swift.String()

  /// The zone in which to create the VM.
  public var zone: Swift.String = Swift.String()

  /// The machine type series to create the VM with.
  public var machineTypeSeries: Swift.String = Swift.String()

  /// The machine type to create the VM with.
  public var machineType: Swift.String = Swift.String()

  /// A list of network tags to associate with the VM.
  public var networkTags: [Swift.String] = []

  /// List of NICs connected to this VM.
  public var networkInterfaces: [NetworkInterface] = []

  /// The service account to associate the VM with.
  public var serviceAccount: Swift.String = Swift.String()

  /// The disk type to use in the VM.
  public var diskType: ComputeEngineDiskType = ComputeEngineDiskType()

  /// A map of labels to associate with the VM.
  public var labels: [Swift.String: Swift.String] = [:]

  /// The license type to use in OS adaptation.
  public var licenseType: ComputeEngineLicenseType = ComputeEngineLicenseType()

  /// The OS license returned from the adaptation module report.
  public var appliedLicense: AppliedLicense? = nil

  /// Compute instance scheduling information (if empty default is used).
  public var computeScheduling: ComputeScheduling? = nil

  /// Defines whether the instance has Secure Boot enabled.
  /// This can be set to true only if the VM boot option is EFI.
  public var secureBoot: Swift.Bool = Swift.Bool()

  /// Optional. Defines whether the instance has vTPM enabled.
  public var enableVtpm: Swift.Bool = Swift.Bool()

  /// Optional. Defines whether the instance has integrity monitoring enabled.
  public var enableIntegrityMonitoring: Swift.Bool = Swift.Bool()

  /// The VM Boot Option, as set in the source VM.
  public var bootOption: ComputeEngineBootOption = ComputeEngineBootOption()

  /// The metadata key/value pairs to assign to the VM.
  public var metadata: [Swift.String: Swift.String] = [:]

  /// Additional licenses to assign to the VM.
  public var additionalLicenses: [Swift.String] = []

  /// The hostname to assign to the VM.
  public var hostname: Swift.String = Swift.String()

  /// Optional. The encryption to apply to the VM disks.
  public var encryption: Encryption? = nil

  /// Optional. By default the virtual machine will keep its existing boot
  /// option. Setting this property will trigger an internal process which will
  /// convert the virtual machine from using the existing boot option to another.
  public var bootConversion: BootConversion = BootConversion()

  /// Optional. Modifiers to be used as configuration of the OS adaptation
  /// process.
  public var adaptationModifiers: [AdaptationModifier] = []

  /// Optional. Additional replica zones of the target regional disks.
  /// If this list is not empty a regional disk will be created. The first
  /// supported zone would be the one stated in the
  /// [zone][google.cloud.vmmigration.v1.ComputeEngineTargetDetails.zone] field.
  /// The rest are taken from this list. Please refer to the [regional disk
  /// creation
  /// API](https://cloud.google.com/compute/docs/regions-zones/global-regional-zonal-resources)
  /// for further details about regional vs zonal disks. If not specified, a
  /// zonal disk will be created in the same zone the VM is created.
  ///
  /// [google.cloud.vmmigration.v1.ComputeEngineTargetDetails.zone]: <doc:ComputeEngineTargetDetails/zone>
  public var diskReplicaZones: [Swift.String] = []

  /// Optional. The storage pool used for the VM disks.
  /// If specified this will be the storage pool in which the disk is created.
  /// This is the full path of the storage pool resource, for example:
  /// "projects/my-project/zones/us-central1-a/storagePools/my-storage-pool".
  /// The storage pool must be in the same project and zone as the target disks.
  /// The storage pool's type must match the disk type.
  public var storagePool: Swift.String = Swift.String()

  /// Initialize a new instance of `ComputeEngineTargetDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeEngineTargetDetails().with { $0.vmName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ComputeEngineTargetDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
