// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ComputeEngineDisksTargetDefaults is a collection of details for creating
/// Persistent Disks in a target Compute Engine project.
public struct ComputeEngineDisksTargetDefaults: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The full path of the resource of type TargetProject which represents the
  /// Compute Engine project in which to create the Persistent Disks.
  public var targetProject: Swift.String = Swift.String()

  /// The details of each Persistent Disk to create.
  public var disks: [PersistentDiskDefaults] = []

  public var location: OneOf_Location? = nil

  /// Details of the VM to attach the disks to as the target of this migration.
  public var vmTarget: OneOf_VmTarget? = nil

  /// Initialize a new instance of `ComputeEngineDisksTargetDefaults`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeEngineDisksTargetDefaults().with { $0.zone = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case zone = "zone"
    case disksTargetDefaults = "disksTargetDefaults"
    case vmTargetDefaults = "vmTargetDefaults"
    case targetProject = "targetProject"
    case disks = "disks"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.targetProject = try container.decode(Swift.String.self, forKey: .targetProject)
    self.disks = try container.decode([PersistentDiskDefaults].self, forKey: .disks)

    var location: OneOf_Location? = nil
    let locationCheckAndSet = {
      if location != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'location'"))
      }
      location = $0
    }
    if let zone = try container.decodeIfPresent(Swift.String.self, forKey: .zone) {
      try locationCheckAndSet(.zone(zone))
    }
    self.location = location

    var vmTarget: OneOf_VmTarget? = nil
    let vmTargetCheckAndSet = {
      if vmTarget != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'vmTarget'"))
      }
      vmTarget = $0
    }
    if let disksTargetDefaults = try container.decodeIfPresent(
      DisksMigrationDisksTargetDefaults?.self, forKey: .disksTargetDefaults)
    {
      try vmTargetCheckAndSet(.disksTargetDefaults(disksTargetDefaults))
    }
    if let vmTargetDefaults = try container.decodeIfPresent(
      DisksMigrationVmTargetDefaults?.self, forKey: .vmTargetDefaults)
    {
      try vmTargetCheckAndSet(.vmTargetDefaults(vmTargetDefaults))
    }
    self.vmTarget = vmTarget
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.targetProject, forKey: .targetProject)
    try container.encode(self.disks, forKey: .disks)

    if let choice = self.location {
      switch choice {
      case .zone(let value):
        try container.encode(value, forKey: .zone)
      }
    }

    if let choice = self.vmTarget {
      switch choice {
      case .disksTargetDefaults(let value):
        try container.encode(value, forKey: .disksTargetDefaults)
      case .vmTargetDefaults(let value):
        try container.encode(value, forKey: .vmTargetDefaults)
      }
    }
  }

  public enum OneOf_Location: Codable, Equatable, Sendable {
    /// The zone in which to create the Persistent Disks.
    case zone(Swift.String)
  }

  /// Details of the VM to attach the disks to as the target of this migration.
  public enum OneOf_VmTarget: Codable, Equatable, Sendable {
    /// Details of the disk only migration target.
    indirect case disksTargetDefaults(DisksMigrationDisksTargetDefaults?)
    /// Details of the VM migration target.
    indirect case vmTargetDefaults(DisksMigrationVmTargetDefaults?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ComputeEngineDisksTargetDefaults"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
