// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// CycleStep holds information about a step progress.
public struct CycleStep: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The time the cycle step has started.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// The time the cycle step has ended.
  public var endTime: GoogleWKT.Timestamp? = nil

  public var step: OneOf_Step? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CycleStep`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CycleStep().with { $0.initializingReplication = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let initializingReplication = CodingKeys(stringValue: "initializingReplication")
    static let replicating = CodingKeys(stringValue: "replicating")
    static let postProcessing = CodingKeys(stringValue: "postProcessing")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")

    static let _knownKeys: Set<Swift.String> = [
      "initializingReplication",
      "replicating",
      "postProcessing",
      "startTime",
      "endTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)

    var step: OneOf_Step? = nil
    let stepCheckAndSet = {
      if step != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'step'"
          ))
      }
      step = $0
    }
    if let initializingReplication = try container.decodeIfPresent(
      InitializingReplicationStep?.self, forKey: .initializingReplication)
    {
      try stepCheckAndSet(.initializingReplication(initializingReplication))
    }
    if let replicating = try container.decodeIfPresent(ReplicatingStep?.self, forKey: .replicating)
    {
      try stepCheckAndSet(.replicating(replicating))
    }
    if let postProcessing = try container.decodeIfPresent(
      PostProcessingStep?.self, forKey: .postProcessing)
    {
      try stepCheckAndSet(.postProcessing(postProcessing))
    }
    self.step = step
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)

    if let choice = self.step {
      switch choice {
      case .initializingReplication(let value):
        try container.encode(value, forKey: .initializingReplication)
      case .replicating(let value):
        try container.encode(value, forKey: .replicating)
      case .postProcessing(let value):
        try container.encode(value, forKey: .postProcessing)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Step: Codable, Equatable, Sendable {
    /// Initializing replication step.
    indirect case initializingReplication(InitializingReplicationStep?)
    /// Replicating step.
    indirect case replicating(ReplicatingStep?)
    /// Post processing step.
    indirect case postProcessing(PostProcessingStep?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.CycleStep"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
