// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// DatacenterConnector message describes a connector between the Source and
/// Google Cloud, which is installed on a vmware datacenter (an OVA vm installed
/// by the user) to connect the Datacenter to Google Cloud and support vm
/// migration data transfer.
public struct DatacenterConnector: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The time the connector was created (as an API call, not when
  /// it was actually installed).
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last time the connector was updated with an API call.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The connector's name.
  public var name: Swift.String = Swift.String()

  /// Immutable. A unique key for this connector. This key is internal to the OVA
  /// connector and is supplied with its creation during the registration process
  /// and can not be modified.
  public var registrationId: Swift.String = Swift.String()

  /// The service account to use in the connector when communicating with the
  /// cloud.
  public var serviceAccount: Swift.String = Swift.String()

  /// The version running in the DatacenterConnector. This is supplied by the OVA
  /// connector during the registration process and can not be modified.
  public var version: Swift.String = Swift.String()

  /// Output only. The communication channel between the datacenter connector and
  /// Google Cloud.
  public var bucket: Swift.String = Swift.String()

  /// Output only. State of the DatacenterConnector, as determined by the health
  /// checks.
  public var state: DatacenterConnector.State = DatacenterConnector.State()

  /// Output only. The time the state was last set.
  public var stateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Provides details on the state of the Datacenter Connector in
  /// case of an error.
  public var error: GoogleRpc.Status? = nil

  /// Output only. Appliance OVA version.
  /// This is the OVA which is manually installed by the user and contains the
  /// infrastructure for the automatically updatable components on the appliance.
  public var applianceInfrastructureVersion: Swift.String = Swift.String()

  /// Output only. Appliance last installed update bundle version.
  /// This is the version of the automatically updatable components on the
  /// appliance.
  public var applianceSoftwareVersion: Swift.String = Swift.String()

  /// Output only. The available versions for updating this appliance.
  public var availableVersions: AvailableUpdates? = nil

  /// Output only. The status of the current / last upgradeAppliance operation.
  public var upgradeStatus: UpgradeStatus? = nil

  /// Initialize a new instance of `DatacenterConnector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DatacenterConnector().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible values of the state.
  public enum State: Codable, Equatable, Sendable {
    /// The state is unknown. This is used for API compatibility only and is not
    /// used by the system.
    case unspecified
    /// The state was not sampled by the health checks yet.
    case pending
    /// The source was sampled by health checks and is not available.
    case offline
    /// The source is available but might not be usable yet due to unvalidated
    /// credentials or another reason. The credentials referred to are the ones
    /// to the Source. The error message will contain further details.
    case failed
    /// The source exists and its credentials were verified.
    case active
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .offline: return 2
      case .failed: return 3
      case .active: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .offline: return "OFFLINE"
      case .failed: return "FAILED"
      case .active: return "ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "OFFLINE": self = .offline
      case "FAILED": self = .failed
      case "ACTIVE": self = .active
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .offline
      case 3: self = .failed
      case 4: self = .active
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .offline: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .active: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.DatacenterConnector"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
