// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DiskMigrationStep holds information about the disk migration step progress.
public struct DiskMigrationStep: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The time the step has started.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time the step has ended.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// The step details.
  public var step: OneOf_Step? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiskMigrationStep`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiskMigrationStep().with { $0.creatingSourceDiskSnapshot = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let creatingSourceDiskSnapshot = CodingKeys(stringValue: "creatingSourceDiskSnapshot")
    static let copyingSourceDiskSnapshot = CodingKeys(stringValue: "copyingSourceDiskSnapshot")
    static let provisioningTargetDisk = CodingKeys(stringValue: "provisioningTargetDisk")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")

    static let _knownKeys: Set<Swift.String> = [
      "creatingSourceDiskSnapshot",
      "copyingSourceDiskSnapshot",
      "provisioningTargetDisk",
      "startTime",
      "endTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)

    var step: OneOf_Step? = nil
    let stepCheckAndSet = {
      if step != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'step'"
          ))
      }
      step = $0
    }
    if let creatingSourceDiskSnapshot = try container.decodeIfPresent(
      CreatingSourceDiskSnapshotStep?.self, forKey: .creatingSourceDiskSnapshot)
    {
      try stepCheckAndSet(.creatingSourceDiskSnapshot(creatingSourceDiskSnapshot))
    }
    if let copyingSourceDiskSnapshot = try container.decodeIfPresent(
      CopyingSourceDiskSnapshotStep?.self, forKey: .copyingSourceDiskSnapshot)
    {
      try stepCheckAndSet(.copyingSourceDiskSnapshot(copyingSourceDiskSnapshot))
    }
    if let provisioningTargetDisk = try container.decodeIfPresent(
      ProvisioningTargetDiskStep?.self, forKey: .provisioningTargetDisk)
    {
      try stepCheckAndSet(.provisioningTargetDisk(provisioningTargetDisk))
    }
    self.step = step
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)

    if let choice = self.step {
      switch choice {
      case .creatingSourceDiskSnapshot(let value):
        try container.encode(value, forKey: .creatingSourceDiskSnapshot)
      case .copyingSourceDiskSnapshot(let value):
        try container.encode(value, forKey: .copyingSourceDiskSnapshot)
      case .provisioningTargetDisk(let value):
        try container.encode(value, forKey: .provisioningTargetDisk)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The step details.
  public enum OneOf_Step: Codable, Equatable, Sendable {
    /// Creating source disk snapshot step.
    indirect case creatingSourceDiskSnapshot(CreatingSourceDiskSnapshotStep?)
    /// Copying source disk snapshot step.
    indirect case copyingSourceDiskSnapshot(CopyingSourceDiskSnapshotStep?)
    /// Creating target disk step.
    indirect case provisioningTargetDisk(ProvisioningTargetDiskStep?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.DiskMigrationStep"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
