// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Details of the target disk in Compute Engine.
public struct DiskMigrationJobTargetDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the resource of type TargetProject which represents
  /// the Compute Engine project in which to create the disk. Should be of the
  /// form: projects/{project}/locations/global/targetProjects/{target-project}
  public var targetProject: Swift.String = Swift.String()

  /// Optional. A map of labels to associate with the disk.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The encryption to apply to the disk.
  /// If the DiskMigrationJob parent Source resource has an encryption, this
  /// field must be set to the same encryption key.
  public var encryption: Encryption? = nil

  /// The target storage.
  public var targetStorage: OneOf_TargetStorage? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiskMigrationJobTargetDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiskMigrationJobTargetDetails().with { $0.targetDisk = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let targetDisk = CodingKeys(stringValue: "targetDisk")
    static let targetProject = CodingKeys(stringValue: "targetProject")
    static let labels = CodingKeys(stringValue: "labels")
    static let encryption = CodingKeys(stringValue: "encryption")

    static let _knownKeys: Set<Swift.String> = [
      "targetDisk",
      "targetProject",
      "labels",
      "encryption",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetProject) {
      self.targetProject = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.encryption = try container.decodeIfPresent(Encryption.self, forKey: .encryption)

    var targetStorage: OneOf_TargetStorage? = nil
    let targetStorageCheckAndSet = {
      if targetStorage != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'targetStorage'"))
      }
      targetStorage = $0
    }
    if let targetDisk = try container.decodeIfPresent(ComputeEngineDisk?.self, forKey: .targetDisk)
    {
      try targetStorageCheckAndSet(.targetDisk(targetDisk))
    }
    self.targetStorage = targetStorage
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.targetProject, forKey: .targetProject)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.encryption, forKey: .encryption)

    if let choice = self.targetStorage {
      switch choice {
      case .targetDisk(let value):
        try container.encode(value, forKey: .targetDisk)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The target storage.
  public enum OneOf_TargetStorage: Codable, Equatable, Sendable {
    /// Required. The target disk.
    indirect case targetDisk(ComputeEngineDisk?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.DiskMigrationJobTargetDetails"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
