// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// DiskMigrationStep holds information about the disk migration step progress.
public struct DiskMigrationStep: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The time the step has started.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time the step has ended.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// The step details.
  public var step: OneOf_Step? = nil

  /// Initialize a new instance of `DiskMigrationStep`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiskMigrationStep().with { $0.creatingSourceDiskSnapshot = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case creatingSourceDiskSnapshot = "creatingSourceDiskSnapshot"
    case copyingSourceDiskSnapshot = "copyingSourceDiskSnapshot"
    case provisioningTargetDisk = "provisioningTargetDisk"
    case startTime = "startTime"
    case endTime = "endTime"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWKT.Timestamp.self, forKey: .endTime)

    var step: OneOf_Step? = nil
    let stepCheckAndSet = {
      if step != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'step'"
          ))
      }
      step = $0
    }
    if let creatingSourceDiskSnapshot = try container.decodeIfPresent(
      CreatingSourceDiskSnapshotStep?.self, forKey: .creatingSourceDiskSnapshot)
    {
      try stepCheckAndSet(.creatingSourceDiskSnapshot(creatingSourceDiskSnapshot))
    }
    if let copyingSourceDiskSnapshot = try container.decodeIfPresent(
      CopyingSourceDiskSnapshotStep?.self, forKey: .copyingSourceDiskSnapshot)
    {
      try stepCheckAndSet(.copyingSourceDiskSnapshot(copyingSourceDiskSnapshot))
    }
    if let provisioningTargetDisk = try container.decodeIfPresent(
      ProvisioningTargetDiskStep?.self, forKey: .provisioningTargetDisk)
    {
      try stepCheckAndSet(.provisioningTargetDisk(provisioningTargetDisk))
    }
    self.step = step
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.startTime, forKey: .startTime)
    try container.encode(self.endTime, forKey: .endTime)

    if let choice = self.step {
      switch choice {
      case .creatingSourceDiskSnapshot(let value):
        try container.encode(value, forKey: .creatingSourceDiskSnapshot)
      case .copyingSourceDiskSnapshot(let value):
        try container.encode(value, forKey: .copyingSourceDiskSnapshot)
      case .provisioningTargetDisk(let value):
        try container.encode(value, forKey: .provisioningTargetDisk)
      }
    }
  }

  /// The step details.
  public enum OneOf_Step: Codable, Equatable, Sendable {
    /// Creating source disk snapshot step.
    indirect case creatingSourceDiskSnapshot(CreatingSourceDiskSnapshotStep?)
    /// Copying source disk snapshot step.
    indirect case copyingSourceDiskSnapshot(CopyingSourceDiskSnapshotStep?)
    /// Creating target disk step.
    indirect case provisioningTargetDisk(ProvisioningTargetDiskStep?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.DiskMigrationStep"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
