// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Parameters affecting the OS adaptation process.
public struct ImageImportOsAdaptationParameters: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Set to true in order to generalize the imported image.
  /// The generalization process enables co-existence of multiple VMs created
  /// from the same image.
  /// For Windows, generalizing the image removes computer-specific information
  /// such as installed drivers and the computer security identifier (SID).
  public var generalize: Swift.Bool = Swift.Bool()

  /// Optional. Choose which type of license to apply to the imported image.
  public var licenseType: ComputeEngineLicenseType = ComputeEngineLicenseType()

  /// Optional. By default the image will keep its existing boot option. Setting
  /// this property will trigger an internal process which will convert the
  /// image from using the existing boot option to another.
  /// The size of the boot disk might be increased to allow the conversion
  public var bootConversion: BootConversion = BootConversion()

  /// Optional. Modifiers to be used as configuration of the OS adaptation
  /// process.
  public var adaptationModifiers: [AdaptationModifier] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImageImportOsAdaptationParameters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageImportOsAdaptationParameters().with { $0.generalize = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let generalize = CodingKeys(stringValue: "generalize")
    static let licenseType = CodingKeys(stringValue: "licenseType")
    static let bootConversion = CodingKeys(stringValue: "bootConversion")
    static let adaptationModifiers = CodingKeys(stringValue: "adaptationModifiers")

    static let _knownKeys: Set<Swift.String> = [
      "generalize",
      "licenseType",
      "bootConversion",
      "adaptationModifiers",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .generalize) {
      self.generalize = value
    }
    if let value = try container.decodeIfPresent(
      ComputeEngineLicenseType.self, forKey: .licenseType)
    {
      self.licenseType = value
    }
    if let value = try container.decodeIfPresent(BootConversion.self, forKey: .bootConversion) {
      self.bootConversion = value
    }
    if let value = try container.decodeIfPresent(
      [AdaptationModifier].self, forKey: .adaptationModifiers)
    {
      self.adaptationModifiers = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.generalize, forKey: .generalize)
    try container.encode(self.licenseType, forKey: .licenseType)
    try container.encode(self.bootConversion, forKey: .bootConversion)
    try container.encode(self.adaptationModifiers, forKey: .adaptationModifiers)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ImageImportOsAdaptationParameters"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
