// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ImageImport describes the configuration of the image import to run.
public struct ImageImport: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource path of the ImageImport.
  public var name: Swift.String = Swift.String()

  /// Output only. The time the image import was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The result of the most recent runs for this ImageImport. All
  /// jobs for this ImageImport can be listed via ListImageImportJobs.
  public var recentImageImportJobs: [ImageImportJob] = []

  /// Immutable. The encryption details used by the image import process during
  /// the image adaptation for Compute Engine.
  public var encryption: Encryption? = nil

  public var source: OneOf_Source? = nil

  /// The configuration of the resources that will be created in GCP as a result
  /// of the ImageImport.
  public var targetDefaults: OneOf_TargetDefaults? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImageImport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageImport().with { $0.cloudStorageUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudStorageUri = CodingKeys(stringValue: "cloudStorageUri")
    static let diskImageTargetDefaults = CodingKeys(stringValue: "diskImageTargetDefaults")
    static let machineImageTargetDefaults = CodingKeys(stringValue: "machineImageTargetDefaults")
    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let recentImageImportJobs = CodingKeys(stringValue: "recentImageImportJobs")
    static let encryption = CodingKeys(stringValue: "encryption")

    static let _knownKeys: Set<Swift.String> = [
      "cloudStorageUri",
      "diskImageTargetDefaults",
      "machineImageTargetDefaults",
      "name",
      "createTime",
      "recentImageImportJobs",
      "encryption",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(
      [ImageImportJob].self, forKey: .recentImageImportJobs)
    {
      self.recentImageImportJobs = value
    }
    self.encryption = try container.decodeIfPresent(Encryption.self, forKey: .encryption)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let cloudStorageUri = try container.decodeIfPresent(
      Swift.String.self, forKey: .cloudStorageUri)
    {
      try sourceCheckAndSet(.cloudStorageUri(cloudStorageUri))
    }
    self.source = source

    var targetDefaults: OneOf_TargetDefaults? = nil
    let targetDefaultsCheckAndSet = {
      if targetDefaults != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'targetDefaults'"))
      }
      targetDefaults = $0
    }
    if let diskImageTargetDefaults = try container.decodeIfPresent(
      DiskImageTargetDetails?.self, forKey: .diskImageTargetDefaults)
    {
      try targetDefaultsCheckAndSet(.diskImageTargetDefaults(diskImageTargetDefaults))
    }
    if let machineImageTargetDefaults = try container.decodeIfPresent(
      MachineImageTargetDetails?.self, forKey: .machineImageTargetDefaults)
    {
      try targetDefaultsCheckAndSet(.machineImageTargetDefaults(machineImageTargetDefaults))
    }
    self.targetDefaults = targetDefaults
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.recentImageImportJobs, forKey: .recentImageImportJobs)
    try container.encodeIfPresent(self.encryption, forKey: .encryption)

    if let choice = self.source {
      switch choice {
      case .cloudStorageUri(let value):
        try container.encode(value, forKey: .cloudStorageUri)
      }
    }

    if let choice = self.targetDefaults {
      switch choice {
      case .diskImageTargetDefaults(let value):
        try container.encode(value, forKey: .diskImageTargetDefaults)
      case .machineImageTargetDefaults(let value):
        try container.encode(value, forKey: .machineImageTargetDefaults)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Immutable. The path to the Cloud Storage file from which the image should
    /// be imported.
    case cloudStorageUri(Swift.String)
  }

  /// The configuration of the resources that will be created in GCP as a result
  /// of the ImageImport.
  public enum OneOf_TargetDefaults: Codable, Equatable, Sendable {
    /// Immutable. Target details for importing a disk image, will be used by
    /// ImageImportJob.
    indirect case diskImageTargetDefaults(DiskImageTargetDetails?)
    /// Immutable. Target details for importing a machine image, will be used by
    /// ImageImportJob.
    indirect case machineImageTargetDefaults(MachineImageTargetDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ImageImport"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
