// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// ImageImportJob describes the progress and result of an image import.
public struct ImageImportJob: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource path of the ImageImportJob.
  public var name: Swift.String = Swift.String()

  /// Output only. The resource paths of the resources created by the image
  /// import job.
  public var createdResources: [Swift.String] = []

  /// Output only. The state of the image import.
  public var state: ImageImportJob.State = ImageImportJob.State()

  /// Output only. The time the image import was created (as an API call, not
  /// when it was actually created in the target).
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time the image import was ended.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Provides details on the error that led to the image import
  /// state in case of an error.
  public var errors: [GoogleRpc.Status] = []

  /// Output only. Warnings that occurred during the image import.
  public var warnings: [MigrationWarning] = []

  /// Output only. The image import steps list representing its progress.
  public var steps: [ImageImportStep] = []

  public var source: OneOf_Source? = nil

  /// The configuration of the resources that were created in GCP as a result of
  /// the image import.
  public var targetDetails: OneOf_TargetDetails? = nil

  /// Initialize a new instance of `ImageImportJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageImportJob().with { $0.cloudStorageUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case cloudStorageUri = "cloudStorageUri"
    case diskImageTargetDetails = "diskImageTargetDetails"
    case machineImageTargetDetails = "machineImageTargetDetails"
    case name = "name"
    case createdResources = "createdResources"
    case state = "state"
    case createTime = "createTime"
    case endTime = "endTime"
    case errors = "errors"
    case warnings = "warnings"
    case steps = "steps"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createdResources = try container.decode([Swift.String].self, forKey: .createdResources)
    self.state = try container.decode(ImageImportJob.State.self, forKey: .state)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .endTime)
    self.errors = try container.decode([GoogleRpc.Status].self, forKey: .errors)
    self.warnings = try container.decode([MigrationWarning].self, forKey: .warnings)
    self.steps = try container.decode([ImageImportStep].self, forKey: .steps)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let cloudStorageUri = try container.decodeIfPresent(
      Swift.String.self, forKey: .cloudStorageUri)
    {
      try sourceCheckAndSet(.cloudStorageUri(cloudStorageUri))
    }
    self.source = source

    var targetDetails: OneOf_TargetDetails? = nil
    let targetDetailsCheckAndSet = {
      if targetDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'targetDetails'"))
      }
      targetDetails = $0
    }
    if let diskImageTargetDetails = try container.decodeIfPresent(
      DiskImageTargetDetails?.self, forKey: .diskImageTargetDetails)
    {
      try targetDetailsCheckAndSet(.diskImageTargetDetails(diskImageTargetDetails))
    }
    if let machineImageTargetDetails = try container.decodeIfPresent(
      MachineImageTargetDetails?.self, forKey: .machineImageTargetDetails)
    {
      try targetDetailsCheckAndSet(.machineImageTargetDetails(machineImageTargetDetails))
    }
    self.targetDetails = targetDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createdResources, forKey: .createdResources)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.endTime, forKey: .endTime)
    try container.encode(self.errors, forKey: .errors)
    try container.encode(self.warnings, forKey: .warnings)
    try container.encode(self.steps, forKey: .steps)

    if let choice = self.source {
      switch choice {
      case .cloudStorageUri(let value):
        try container.encode(value, forKey: .cloudStorageUri)
      }
    }

    if let choice = self.targetDetails {
      switch choice {
      case .diskImageTargetDetails(let value):
        try container.encode(value, forKey: .diskImageTargetDetails)
      case .machineImageTargetDetails(let value):
        try container.encode(value, forKey: .machineImageTargetDetails)
      }
    }
  }

  /// Possible states of the image import.
  public enum State: Codable, Equatable, Sendable {
    /// The state is unknown.
    case unspecified
    /// The image import has not yet started.
    case pending
    /// The image import is active and running.
    case running
    /// The image import has finished successfully.
    case succeeded
    /// The image import has finished with errors.
    case failed
    /// The image import is being cancelled.
    case cancelling
    /// The image import was cancelled.
    case cancelled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .running: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .cancelling: return 5
      case .cancelled: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .cancelling: return "CANCELLING"
      case .cancelled: return "CANCELLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "CANCELLING": self = .cancelling
      case "CANCELLED": self = .cancelled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .running
      case 3: self = .succeeded
      case 4: self = .failed
      case 5: self = .cancelling
      case 6: self = .cancelled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .running: return try container.encode(2)
      case .succeeded: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .cancelling: return try container.encode(5)
      case .cancelled: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Output only. The path to the Cloud Storage file from which the image
    /// should be imported.
    case cloudStorageUri(Swift.String)
  }

  /// The configuration of the resources that were created in GCP as a result of
  /// the image import.
  public enum OneOf_TargetDetails: Codable, Equatable, Sendable {
    /// Output only. Target details used to import a disk image.
    indirect case diskImageTargetDetails(DiskImageTargetDetails?)
    /// Output only. Target details used to import a machine image.
    indirect case machineImageTargetDetails(MachineImageTargetDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ImageImportJob"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
