// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// ImageImportStep holds information about the image import step progress.
public struct ImageImportStep: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The time the step has started.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time the step has ended.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  public var step: OneOf_Step? = nil

  /// Initialize a new instance of `ImageImportStep`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageImportStep().with { $0.initializing = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case initializing = "initializing"
    case loadingSourceFiles = "loadingSourceFiles"
    case adaptingOs = "adaptingOs"
    case creatingImage = "creatingImage"
    case startTime = "startTime"
    case endTime = "endTime"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .endTime)

    var step: OneOf_Step? = nil
    let stepCheckAndSet = {
      if step != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'step'"
          ))
      }
      step = $0
    }
    if let initializing = try container.decodeIfPresent(
      InitializingImageImportStep?.self, forKey: .initializing)
    {
      try stepCheckAndSet(.initializing(initializing))
    }
    if let loadingSourceFiles = try container.decodeIfPresent(
      LoadingImageSourceFilesStep?.self, forKey: .loadingSourceFiles)
    {
      try stepCheckAndSet(.loadingSourceFiles(loadingSourceFiles))
    }
    if let adaptingOs = try container.decodeIfPresent(AdaptingOSStep?.self, forKey: .adaptingOs) {
      try stepCheckAndSet(.adaptingOs(adaptingOs))
    }
    if let creatingImage = try container.decodeIfPresent(
      CreatingImageStep?.self, forKey: .creatingImage)
    {
      try stepCheckAndSet(.creatingImage(creatingImage))
    }
    self.step = step
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.startTime, forKey: .startTime)
    try container.encode(self.endTime, forKey: .endTime)

    if let choice = self.step {
      switch choice {
      case .initializing(let value):
        try container.encode(value, forKey: .initializing)
      case .loadingSourceFiles(let value):
        try container.encode(value, forKey: .loadingSourceFiles)
      case .adaptingOs(let value):
        try container.encode(value, forKey: .adaptingOs)
      case .creatingImage(let value):
        try container.encode(value, forKey: .creatingImage)
      }
    }
  }

  public enum OneOf_Step: Codable, Equatable, Sendable {
    /// Initializing step.
    indirect case initializing(InitializingImageImportStep?)
    /// Loading source files step.
    indirect case loadingSourceFiles(LoadingImageSourceFilesStep?)
    /// Adapting OS step.
    indirect case adaptingOs(AdaptingOSStep?)
    /// Creating image step.
    indirect case creatingImage(CreatingImageStep?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ImageImportStep"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
