// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The target details of the machine image resource that will be created by the
/// image import job.
public struct MachineImageTargetDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the machine image to be created.
  public var machineImageName: Swift.String = Swift.String()

  /// Required. Reference to the TargetProject resource that represents the
  /// target project in which the imported machine image will be created.
  public var targetProject: Swift.String = Swift.String()

  /// Optional. An optional description of the machine image.
  public var description: Swift.String = Swift.String()

  /// Optional. Set to true to set the machine image storageLocations to the
  /// single region of the import job. When false, the closest multi-region is
  /// selected.
  public var singleRegionStorage: Swift.Bool = Swift.Bool()

  /// Immutable. The encryption to apply to the machine image.
  /// If the Image Import resource has an encryption, this field must be set to
  /// the same encryption key.
  public var encryption: Encryption? = nil

  /// Optional. Parameters overriding decisions based on the source machine image
  /// configurations.
  public var machineImageParametersOverrides: MachineImageParametersOverrides? = nil

  /// Optional. The service account to assign to the instance created by the
  /// machine image.
  public var serviceAccount: ServiceAccount? = nil

  /// Optional. Additional licenses to assign to the instance created by the
  /// machine image. Format:
  /// https://www.googleapis.com/compute/v1/projects/PROJECT_ID/global/licenses/LICENSE_NAME
  /// Or
  /// https://www.googleapis.com/compute/beta/projects/PROJECT_ID/global/licenses/LICENSE_NAME
  public var additionalLicenses: [Swift.String] = []

  /// Optional. The labels to apply to the instance created by the machine image.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The tags to apply to the instance created by the machine image.
  public var tags: [Swift.String] = []

  /// Optional. Shielded instance configuration.
  public var shieldedInstanceConfig: ShieldedInstanceConfig? = nil

  /// Optional. The network interfaces to create with the instance created by the
  /// machine image. Internal and external IP addresses, and network tiers are
  /// ignored for machine image import.
  public var networkInterfaces: [NetworkInterface] = []

  public var osAdaptationConfig: OneOf_OsAdaptationConfig? = nil

  /// Initialize a new instance of `MachineImageTargetDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MachineImageTargetDetails().with { $0.osAdaptationParameters = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case osAdaptationParameters = "osAdaptationParameters"
    case skipOsAdaptation = "skipOsAdaptation"
    case machineImageName = "machineImageName"
    case targetProject = "targetProject"
    case description = "description"
    case singleRegionStorage = "singleRegionStorage"
    case encryption = "encryption"
    case machineImageParametersOverrides = "machineImageParametersOverrides"
    case serviceAccount = "serviceAccount"
    case additionalLicenses = "additionalLicenses"
    case labels = "labels"
    case tags = "tags"
    case shieldedInstanceConfig = "shieldedInstanceConfig"
    case networkInterfaces = "networkInterfaces"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.machineImageName = try container.decode(Swift.String.self, forKey: .machineImageName)
    self.targetProject = try container.decode(Swift.String.self, forKey: .targetProject)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.singleRegionStorage = try container.decode(Swift.Bool.self, forKey: .singleRegionStorage)
    self.encryption = try container.decodeIfPresent(Encryption.self, forKey: .encryption)
    self.machineImageParametersOverrides = try container.decodeIfPresent(
      MachineImageParametersOverrides.self, forKey: .machineImageParametersOverrides)
    self.serviceAccount = try container.decodeIfPresent(
      ServiceAccount.self, forKey: .serviceAccount)
    self.additionalLicenses = try container.decode([Swift.String].self, forKey: .additionalLicenses)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.tags = try container.decode([Swift.String].self, forKey: .tags)
    self.shieldedInstanceConfig = try container.decodeIfPresent(
      ShieldedInstanceConfig.self, forKey: .shieldedInstanceConfig)
    self.networkInterfaces = try container.decode(
      [NetworkInterface].self, forKey: .networkInterfaces)

    var osAdaptationConfig: OneOf_OsAdaptationConfig? = nil
    let osAdaptationConfigCheckAndSet = {
      if osAdaptationConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'osAdaptationConfig'"))
      }
      osAdaptationConfig = $0
    }
    if let osAdaptationParameters = try container.decodeIfPresent(
      ImageImportOsAdaptationParameters?.self, forKey: .osAdaptationParameters)
    {
      try osAdaptationConfigCheckAndSet(.osAdaptationParameters(osAdaptationParameters))
    }
    if let skipOsAdaptation = try container.decodeIfPresent(
      SkipOsAdaptation?.self, forKey: .skipOsAdaptation)
    {
      try osAdaptationConfigCheckAndSet(.skipOsAdaptation(skipOsAdaptation))
    }
    self.osAdaptationConfig = osAdaptationConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.machineImageName, forKey: .machineImageName)
    try container.encode(self.targetProject, forKey: .targetProject)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.singleRegionStorage, forKey: .singleRegionStorage)
    try container.encode(self.encryption, forKey: .encryption)
    try container.encode(
      self.machineImageParametersOverrides, forKey: .machineImageParametersOverrides)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.additionalLicenses, forKey: .additionalLicenses)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.shieldedInstanceConfig, forKey: .shieldedInstanceConfig)
    try container.encode(self.networkInterfaces, forKey: .networkInterfaces)

    if let choice = self.osAdaptationConfig {
      switch choice {
      case .osAdaptationParameters(let value):
        try container.encode(value, forKey: .osAdaptationParameters)
      case .skipOsAdaptation(let value):
        try container.encode(value, forKey: .skipOsAdaptation)
      }
    }
  }

  public enum OneOf_OsAdaptationConfig: Codable, Equatable, Sendable {
    /// Optional. Use to set the parameters relevant for the OS adaptation
    /// process.
    indirect case osAdaptationParameters(ImageImportOsAdaptationParameters?)
    /// Optional. Use to skip OS adaptation process.
    indirect case skipOsAdaptation(SkipOsAdaptation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.MachineImageTargetDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
