// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// NetworkInterface represents a NIC of a VM.
public struct NetworkInterface: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The network to connect the NIC to.
  public var network: Swift.String = Swift.String()

  /// Optional. The subnetwork to connect the NIC to.
  public var subnetwork: Swift.String = Swift.String()

  /// Optional. The internal IP to define in the NIC.
  /// The formats accepted are: `ephemeral` \ ipv4 address \ a named address
  /// resource full path.
  public var internalIp: Swift.String = Swift.String()

  /// Optional. The external IP to define in the NIC.
  public var externalIp: Swift.String = Swift.String()

  /// Optional. The networking tier used for optimizing connectivity between
  /// instances and systems on the internet. Applies only for external ephemeral
  /// IP addresses. If left empty, will default to PREMIUM.
  public var networkTier: ComputeEngineNetworkTier = ComputeEngineNetworkTier()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `NetworkInterface`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkInterface().with { $0.network = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let network = CodingKeys(stringValue: "network")
    static let subnetwork = CodingKeys(stringValue: "subnetwork")
    static let internalIp = CodingKeys(stringValue: "internalIp")
    static let externalIp = CodingKeys(stringValue: "externalIp")
    static let networkTier = CodingKeys(stringValue: "networkTier")

    static let _knownKeys: Set<Swift.String> = [
      "network",
      "subnetwork",
      "internalIp",
      "externalIp",
      "networkTier",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetwork) {
      self.subnetwork = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .internalIp) {
      self.internalIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .externalIp) {
      self.externalIp = value
    }
    if let value = try container.decodeIfPresent(
      ComputeEngineNetworkTier.self, forKey: .networkTier)
    {
      self.networkTier = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.subnetwork, forKey: .subnetwork)
    try container.encode(self.internalIp, forKey: .internalIp)
    try container.encode(self.externalIp, forKey: .externalIp)
    try container.encode(self.networkTier, forKey: .networkTier)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.NetworkInterface"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
