// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// VM operating system (OS) capabilities needed for determining compatibility
/// with Compute Engine features supported by the migration.
public enum OsCapability: Codable, Equatable, Sendable {
  /// This is for API compatibility only and is not in use.
  case unspecified
  /// NVMe driver installed and the VM can use NVMe PD or local SSD.
  case nvmeStorageAccess
  /// gVNIC virtual NIC driver supported.
  case gvnicNetworkInterface
  /// IDPF virtual NIC driver supported.
  case idpfNetworkInterface
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .nvmeStorageAccess: return 1
    case .gvnicNetworkInterface: return 2
    case .idpfNetworkInterface: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "OS_CAPABILITY_UNSPECIFIED"
    case .nvmeStorageAccess: return "OS_CAPABILITY_NVME_STORAGE_ACCESS"
    case .gvnicNetworkInterface: return "OS_CAPABILITY_GVNIC_NETWORK_INTERFACE"
    case .idpfNetworkInterface: return "OS_CAPABILITY_IDPF_NETWORK_INTERFACE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OsCapability/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "OS_CAPABILITY_UNSPECIFIED": self = .unspecified
    case "OS_CAPABILITY_NVME_STORAGE_ACCESS": self = .nvmeStorageAccess
    case "OS_CAPABILITY_GVNIC_NETWORK_INTERFACE": self = .gvnicNetworkInterface
    case "OS_CAPABILITY_IDPF_NETWORK_INTERFACE": self = .idpfNetworkInterface
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OsCapability/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .nvmeStorageAccess
    case 2: self = .gvnicNetworkInterface
    case 3: self = .idpfNetworkInterface
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .nvmeStorageAccess: return try container.encode(1)
    case .gvnicNetworkInterface: return try container.encode(2)
    case .idpfNetworkInterface: return try container.encode(3)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
