// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// ReplicatingStep contains specific step details.
public struct ReplicatingStep: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Total bytes to be handled in the step.
  public var totalBytes: Swift.Int64 = Swift.Int64()

  /// Replicated bytes in the step.
  public var replicatedBytes: Swift.Int64 = Swift.Int64()

  /// The source disks replication rate for the last 2 minutes in bytes per
  /// second.
  public var lastTwoMinutesAverageBytesPerSecond: Swift.Int64 = Swift.Int64()

  /// The source disks replication rate for the last 30 minutes in bytes per
  /// second.
  public var lastThirtyMinutesAverageBytesPerSecond: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReplicatingStep`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplicatingStep().with { $0.totalBytes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let totalBytes = CodingKeys(stringValue: "totalBytes")
    static let replicatedBytes = CodingKeys(stringValue: "replicatedBytes")
    static let lastTwoMinutesAverageBytesPerSecond = CodingKeys(
      stringValue: "lastTwoMinutesAverageBytesPerSecond")
    static let lastThirtyMinutesAverageBytesPerSecond = CodingKeys(
      stringValue: "lastThirtyMinutesAverageBytesPerSecond")

    static let _knownKeys: Set<Swift.String> = [
      "totalBytes",
      "replicatedBytes",
      "lastTwoMinutesAverageBytesPerSecond",
      "lastThirtyMinutesAverageBytesPerSecond",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalBytes) {
      self.totalBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .replicatedBytes) {
      self.replicatedBytes = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .lastTwoMinutesAverageBytesPerSecond)
    {
      self.lastTwoMinutesAverageBytesPerSecond = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .lastThirtyMinutesAverageBytesPerSecond)
    {
      self.lastThirtyMinutesAverageBytesPerSecond = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.totalBytes, forKey: .totalBytes)
    try container.encode(self.replicatedBytes, forKey: .replicatedBytes)
    try container.encode(
      self.lastTwoMinutesAverageBytesPerSecond, forKey: .lastTwoMinutesAverageBytesPerSecond)
    try container.encode(
      self.lastThirtyMinutesAverageBytesPerSecond, forKey: .lastThirtyMinutesAverageBytesPerSecond)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ReplicatingStep"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
