// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// ReplicationCycle contains information about the current replication cycle
/// status.
public struct ReplicationCycle: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The identifier of the ReplicationCycle.
  public var name: Swift.String = Swift.String()

  /// The cycle's ordinal number.
  public var cycleNumber: Swift.Int32 = Swift.Int32()

  /// The time the replication cycle has started.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// The time the replication cycle has ended.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// The accumulated duration the replication cycle was paused.
  public var totalPauseDuration: GoogleCloudWkt.Duration? = nil

  /// The current progress in percentage of this cycle.
  /// Was replaced by 'steps' field, which breaks down the cycle progression more
  /// accurately.
  @available(*, deprecated)
  public var progressPercent: Swift.Int32 = Swift.Int32()

  /// The cycle's steps list representing its progress.
  public var steps: [CycleStep] = []

  /// State of the ReplicationCycle.
  public var state: ReplicationCycle.State = ReplicationCycle.State()

  /// Output only. Provides details on the state of the cycle in case of an
  /// error.
  public var error: GoogleRpc.Status? = nil

  /// Output only. Warnings that occurred during the cycle.
  public var warnings: [MigrationWarning] = []

  /// Initialize a new instance of `ReplicationCycle`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplicationCycle().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible states of a replication cycle.
  public enum State: Codable, Equatable, Sendable {
    /// The state is unknown. This is used for API compatibility only and is not
    /// used by the system.
    case unspecified
    /// The replication cycle is running.
    case running
    /// The replication cycle is paused.
    case paused
    /// The replication cycle finished with errors.
    case failed
    /// The replication cycle finished successfully.
    case succeeded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .running: return 1
      case .paused: return 2
      case .failed: return 3
      case .succeeded: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .running: return "RUNNING"
      case .paused: return "PAUSED"
      case .failed: return "FAILED"
      case .succeeded: return "SUCCEEDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "RUNNING": self = .running
      case "PAUSED": self = .paused
      case "FAILED": self = .failed
      case "SUCCEEDED": self = .succeeded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .running
      case 2: self = .paused
      case 3: self = .failed
      case 4: self = .succeeded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .running: return try container.encode(1)
      case .paused: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .succeeded: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.ReplicationCycle"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
