// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Source message describes a specific vm migration Source resource. It contains
/// the source environment information.
public struct Source: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The Source name.
  public var name: Swift.String = Swift.String()

  /// Output only. The create time timestamp.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The update time timestamp.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// The labels of the source.
  public var labels: [Swift.String: Swift.String] = [:]

  /// User-provided description of the source.
  public var description: Swift.String = Swift.String()

  /// Optional. Immutable. The encryption details of the source data stored by
  /// the service.
  public var encryption: Encryption? = nil

  public var sourceDetails: OneOf_SourceDetails? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Source`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Source().with { $0.vmware = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vmware = CodingKeys(stringValue: "vmware")
    static let aws = CodingKeys(stringValue: "aws")
    static let azure = CodingKeys(stringValue: "azure")
    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let encryption = CodingKeys(stringValue: "encryption")

    static let _knownKeys: Set<Swift.String> = [
      "vmware",
      "aws",
      "azure",
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "encryption",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.encryption = try container.decodeIfPresent(Encryption.self, forKey: .encryption)

    var sourceDetails: OneOf_SourceDetails? = nil
    let sourceDetailsCheckAndSet = {
      if sourceDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sourceDetails'"))
      }
      sourceDetails = $0
    }
    if let vmware = try container.decodeIfPresent(VmwareSourceDetails?.self, forKey: .vmware) {
      try sourceDetailsCheckAndSet(.vmware(vmware))
    }
    if let aws = try container.decodeIfPresent(AwsSourceDetails?.self, forKey: .aws) {
      try sourceDetailsCheckAndSet(.aws(aws))
    }
    if let azure = try container.decodeIfPresent(AzureSourceDetails?.self, forKey: .azure) {
      try sourceDetailsCheckAndSet(.azure(azure))
    }
    self.sourceDetails = sourceDetails
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.encryption, forKey: .encryption)

    if let choice = self.sourceDetails {
      switch choice {
      case .vmware(let value):
        try container.encode(value, forKey: .vmware)
      case .aws(let value):
        try container.encode(value, forKey: .aws)
      case .azure(let value):
        try container.encode(value, forKey: .azure)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_SourceDetails: Codable, Equatable, Sendable {
    /// Vmware type source details.
    indirect case vmware(VmwareSourceDetails?)
    /// AWS type source details.
    indirect case aws(AwsSourceDetails?)
    /// Azure type source details.
    indirect case azure(AzureSourceDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.Source"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
