// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// SourceStorageResource describes a storage resource in the source.
public struct SourceStorageResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Source storage resource details.
  public var storageResource: OneOf_StorageResource? = nil

  /// Initialize a new instance of `SourceStorageResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SourceStorageResource().with { $0.awsDiskDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case awsDiskDetails = "awsDiskDetails"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var storageResource: OneOf_StorageResource? = nil
    let storageResourceCheckAndSet = {
      if storageResource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'storageResource'"))
      }
      storageResource = $0
    }
    if let awsDiskDetails = try container.decodeIfPresent(
      AwsSourceDiskDetails?.self, forKey: .awsDiskDetails)
    {
      try storageResourceCheckAndSet(.awsDiskDetails(awsDiskDetails))
    }
    self.storageResource = storageResource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.storageResource {
      switch choice {
      case .awsDiskDetails(let value):
        try container.encode(value, forKey: .awsDiskDetails)
      }
    }
  }

  /// Source storage resource details.
  public enum OneOf_StorageResource: Codable, Equatable, Sendable {
    /// Source AWS volume details.
    indirect case awsDiskDetails(AwsSourceDiskDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.SourceStorageResource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
