// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class VmMigrationLogging: VmMigrationStub {
    let inner: any VmMigrationStub
    let logger: Logger

    public init(_ inner: any VmMigrationStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-vmmigration-v1"
      logger[metadataKey: "gcp.client.service"] = "vmmigration"
      logger[metadataKey: "gcp.experimental.swift.client"] = "VmMigration"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listSources(
      request: ListSourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSources",
        action: {
          (r: ListSourcesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListSourcesResponse
          in
          return try await self.inner.listSources(request: r, options: o)
        })
    }

    public func getSource(
      request: GetSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.Source {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSource",
        action: {
          (r: GetSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.Source
          in
          return try await self.inner.getSource(request: r, options: o)
        })
    }

    public func createSource(
      request: CreateSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSource",
        action: {
          (r: CreateSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createSource(request: r, options: o)
        })
    }

    public func updateSource(
      request: UpdateSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSource",
        action: {
          (r: UpdateSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateSource(request: r, options: o)
        })
    }

    public func deleteSource(
      request: DeleteSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSource",
        action: {
          (r: DeleteSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteSource(request: r, options: o)
        })
    }

    public func fetchInventory(
      request: FetchInventoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.FetchInventoryResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchInventory",
        action: {
          (r: FetchInventoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.FetchInventoryResponse
          in
          return try await self.inner.fetchInventory(request: r, options: o)
        })
    }

    public func fetchStorageInventory(
      request: FetchStorageInventoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.FetchStorageInventoryResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchStorageInventory",
        action: {
          (r: FetchStorageInventoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.FetchStorageInventoryResponse
          in
          return try await self.inner.fetchStorageInventory(request: r, options: o)
        })
    }

    public func listUtilizationReports(
      request: ListUtilizationReportsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListUtilizationReportsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listUtilizationReports",
        action: {
          (r: ListUtilizationReportsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListUtilizationReportsResponse
          in
          return try await self.inner.listUtilizationReports(request: r, options: o)
        })
    }

    public func getUtilizationReport(
      request: GetUtilizationReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.UtilizationReport {
      try await self._intercept(
        request: request,
        options: options,
        name: "getUtilizationReport",
        action: {
          (r: GetUtilizationReportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.UtilizationReport
          in
          return try await self.inner.getUtilizationReport(request: r, options: o)
        })
    }

    public func createUtilizationReport(
      request: CreateUtilizationReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createUtilizationReport",
        action: {
          (r: CreateUtilizationReportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createUtilizationReport(request: r, options: o)
        })
    }

    public func deleteUtilizationReport(
      request: DeleteUtilizationReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteUtilizationReport",
        action: {
          (r: DeleteUtilizationReportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteUtilizationReport(request: r, options: o)
        })
    }

    public func listDatacenterConnectors(
      request: ListDatacenterConnectorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListDatacenterConnectorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDatacenterConnectors",
        action: {
          (r: ListDatacenterConnectorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListDatacenterConnectorsResponse
          in
          return try await self.inner.listDatacenterConnectors(request: r, options: o)
        })
    }

    public func getDatacenterConnector(
      request: GetDatacenterConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.DatacenterConnector {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDatacenterConnector",
        action: {
          (r: GetDatacenterConnectorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.DatacenterConnector
          in
          return try await self.inner.getDatacenterConnector(request: r, options: o)
        })
    }

    public func createDatacenterConnector(
      request: CreateDatacenterConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDatacenterConnector",
        action: {
          (r: CreateDatacenterConnectorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDatacenterConnector(request: r, options: o)
        })
    }

    public func deleteDatacenterConnector(
      request: DeleteDatacenterConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDatacenterConnector",
        action: {
          (r: DeleteDatacenterConnectorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDatacenterConnector(request: r, options: o)
        })
    }

    public func upgradeAppliance(
      request: UpgradeApplianceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "upgradeAppliance",
        action: {
          (r: UpgradeApplianceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.upgradeAppliance(request: r, options: o)
        })
    }

    public func createMigratingVm(
      request: CreateMigratingVmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createMigratingVm",
        action: {
          (r: CreateMigratingVmRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMigratingVm(request: r, options: o)
        })
    }

    public func listMigratingVms(
      request: ListMigratingVmsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListMigratingVmsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMigratingVms",
        action: {
          (r: ListMigratingVmsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListMigratingVmsResponse
          in
          return try await self.inner.listMigratingVms(request: r, options: o)
        })
    }

    public func getMigratingVm(
      request: GetMigratingVmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.MigratingVm {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMigratingVm",
        action: {
          (r: GetMigratingVmRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.MigratingVm
          in
          return try await self.inner.getMigratingVm(request: r, options: o)
        })
    }

    public func updateMigratingVm(
      request: UpdateMigratingVmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateMigratingVm",
        action: {
          (r: UpdateMigratingVmRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMigratingVm(request: r, options: o)
        })
    }

    public func deleteMigratingVm(
      request: DeleteMigratingVmRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteMigratingVm",
        action: {
          (r: DeleteMigratingVmRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMigratingVm(request: r, options: o)
        })
    }

    public func startMigration(
      request: StartMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "startMigration",
        action: {
          (r: StartMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startMigration(request: r, options: o)
        })
    }

    public func resumeMigration(
      request: ResumeMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "resumeMigration",
        action: {
          (r: ResumeMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resumeMigration(request: r, options: o)
        })
    }

    public func pauseMigration(
      request: PauseMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "pauseMigration",
        action: {
          (r: PauseMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.pauseMigration(request: r, options: o)
        })
    }

    public func finalizeMigration(
      request: FinalizeMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "finalizeMigration",
        action: {
          (r: FinalizeMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.finalizeMigration(request: r, options: o)
        })
    }

    public func extendMigration(
      request: ExtendMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "extendMigration",
        action: {
          (r: ExtendMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.extendMigration(request: r, options: o)
        })
    }

    public func createCloneJob(
      request: CreateCloneJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCloneJob",
        action: {
          (r: CreateCloneJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCloneJob(request: r, options: o)
        })
    }

    public func cancelCloneJob(
      request: CancelCloneJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelCloneJob",
        action: {
          (r: CancelCloneJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.cancelCloneJob(request: r, options: o)
        })
    }

    public func listCloneJobs(
      request: ListCloneJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListCloneJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCloneJobs",
        action: {
          (r: ListCloneJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListCloneJobsResponse
          in
          return try await self.inner.listCloneJobs(request: r, options: o)
        })
    }

    public func getCloneJob(
      request: GetCloneJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.CloneJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCloneJob",
        action: {
          (r: GetCloneJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.CloneJob
          in
          return try await self.inner.getCloneJob(request: r, options: o)
        })
    }

    public func createCutoverJob(
      request: CreateCutoverJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCutoverJob",
        action: {
          (r: CreateCutoverJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCutoverJob(request: r, options: o)
        })
    }

    public func cancelCutoverJob(
      request: CancelCutoverJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelCutoverJob",
        action: {
          (r: CancelCutoverJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.cancelCutoverJob(request: r, options: o)
        })
    }

    public func listCutoverJobs(
      request: ListCutoverJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListCutoverJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCutoverJobs",
        action: {
          (r: ListCutoverJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListCutoverJobsResponse
          in
          return try await self.inner.listCutoverJobs(request: r, options: o)
        })
    }

    public func getCutoverJob(
      request: GetCutoverJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.CutoverJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCutoverJob",
        action: {
          (r: GetCutoverJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.CutoverJob
          in
          return try await self.inner.getCutoverJob(request: r, options: o)
        })
    }

    public func listGroups(
      request: ListGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGroups",
        action: {
          (r: ListGroupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListGroupsResponse
          in
          return try await self.inner.listGroups(request: r, options: o)
        })
    }

    public func getGroup(
      request: GetGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.Group {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGroup",
        action: {
          (r: GetGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.Group
          in
          return try await self.inner.getGroup(request: r, options: o)
        })
    }

    public func createGroup(
      request: CreateGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createGroup",
        action: {
          (r: CreateGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGroup(request: r, options: o)
        })
    }

    public func updateGroup(
      request: UpdateGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateGroup",
        action: {
          (r: UpdateGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGroup(request: r, options: o)
        })
    }

    public func deleteGroup(
      request: DeleteGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteGroup",
        action: {
          (r: DeleteGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGroup(request: r, options: o)
        })
    }

    public func addGroupMigration(
      request: AddGroupMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "addGroupMigration",
        action: {
          (r: AddGroupMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.addGroupMigration(request: r, options: o)
        })
    }

    public func removeGroupMigration(
      request: RemoveGroupMigrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "removeGroupMigration",
        action: {
          (r: RemoveGroupMigrationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.removeGroupMigration(request: r, options: o)
        })
    }

    public func listTargetProjects(
      request: ListTargetProjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListTargetProjectsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTargetProjects",
        action: {
          (r: ListTargetProjectsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListTargetProjectsResponse
          in
          return try await self.inner.listTargetProjects(request: r, options: o)
        })
    }

    public func getTargetProject(
      request: GetTargetProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.TargetProject {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTargetProject",
        action: {
          (r: GetTargetProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.TargetProject
          in
          return try await self.inner.getTargetProject(request: r, options: o)
        })
    }

    public func createTargetProject(
      request: CreateTargetProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTargetProject",
        action: {
          (r: CreateTargetProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createTargetProject(request: r, options: o)
        })
    }

    public func updateTargetProject(
      request: UpdateTargetProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTargetProject",
        action: {
          (r: UpdateTargetProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateTargetProject(request: r, options: o)
        })
    }

    public func deleteTargetProject(
      request: DeleteTargetProjectRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTargetProject",
        action: {
          (r: DeleteTargetProjectRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteTargetProject(request: r, options: o)
        })
    }

    public func listReplicationCycles(
      request: ListReplicationCyclesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListReplicationCyclesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listReplicationCycles",
        action: {
          (r: ListReplicationCyclesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListReplicationCyclesResponse
          in
          return try await self.inner.listReplicationCycles(request: r, options: o)
        })
    }

    public func getReplicationCycle(
      request: GetReplicationCycleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ReplicationCycle {
      try await self._intercept(
        request: request,
        options: options,
        name: "getReplicationCycle",
        action: {
          (r: GetReplicationCycleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ReplicationCycle
          in
          return try await self.inner.getReplicationCycle(request: r, options: o)
        })
    }

    public func listImageImports(
      request: ListImageImportsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListImageImportsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listImageImports",
        action: {
          (r: ListImageImportsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListImageImportsResponse
          in
          return try await self.inner.listImageImports(request: r, options: o)
        })
    }

    public func getImageImport(
      request: GetImageImportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ImageImport {
      try await self._intercept(
        request: request,
        options: options,
        name: "getImageImport",
        action: {
          (r: GetImageImportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ImageImport
          in
          return try await self.inner.getImageImport(request: r, options: o)
        })
    }

    public func createImageImport(
      request: CreateImageImportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createImageImport",
        action: {
          (r: CreateImageImportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createImageImport(request: r, options: o)
        })
    }

    public func deleteImageImport(
      request: DeleteImageImportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteImageImport",
        action: {
          (r: DeleteImageImportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteImageImport(request: r, options: o)
        })
    }

    public func listImageImportJobs(
      request: ListImageImportJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListImageImportJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listImageImportJobs",
        action: {
          (r: ListImageImportJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListImageImportJobsResponse
          in
          return try await self.inner.listImageImportJobs(request: r, options: o)
        })
    }

    public func getImageImportJob(
      request: GetImageImportJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ImageImportJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getImageImportJob",
        action: {
          (r: GetImageImportJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ImageImportJob
          in
          return try await self.inner.getImageImportJob(request: r, options: o)
        })
    }

    public func cancelImageImportJob(
      request: CancelImageImportJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelImageImportJob",
        action: {
          (r: CancelImageImportJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.cancelImageImportJob(request: r, options: o)
        })
    }

    public func createDiskMigrationJob(
      request: CreateDiskMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDiskMigrationJob",
        action: {
          (r: CreateDiskMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDiskMigrationJob(request: r, options: o)
        })
    }

    public func listDiskMigrationJobs(
      request: ListDiskMigrationJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.ListDiskMigrationJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDiskMigrationJobs",
        action: {
          (r: ListDiskMigrationJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.ListDiskMigrationJobsResponse
          in
          return try await self.inner.listDiskMigrationJobs(request: r, options: o)
        })
    }

    public func getDiskMigrationJob(
      request: GetDiskMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVMMigrationV1.DiskMigrationJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDiskMigrationJob",
        action: {
          (r: GetDiskMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVMMigrationV1.DiskMigrationJob
          in
          return try await self.inner.getDiskMigrationJob(request: r, options: o)
        })
    }

    public func updateDiskMigrationJob(
      request: UpdateDiskMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDiskMigrationJob",
        action: {
          (r: UpdateDiskMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDiskMigrationJob(request: r, options: o)
        })
    }

    public func deleteDiskMigrationJob(
      request: DeleteDiskMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDiskMigrationJob",
        action: {
          (r: DeleteDiskMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDiskMigrationJob(request: r, options: o)
        })
    }

    public func runDiskMigrationJob(
      request: RunDiskMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "runDiskMigrationJob",
        action: {
          (r: RunDiskMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.runDiskMigrationJob(request: r, options: o)
        })
    }

    public func cancelDiskMigrationJob(
      request: CancelDiskMigrationJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelDiskMigrationJob",
        action: {
          (r: CancelDiskMigrationJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.cancelDiskMigrationJob(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
