// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Utilization metrics values for a single VM.
public struct VmUtilizationMetrics: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Max CPU usage, percent.
  public var cpuMaxPercent: Swift.Int32 = Swift.Int32()

  /// Average CPU usage, percent.
  public var cpuAveragePercent: Swift.Int32 = Swift.Int32()

  /// Max memory usage, percent.
  public var memoryMaxPercent: Swift.Int32 = Swift.Int32()

  /// Average memory usage, percent.
  public var memoryAveragePercent: Swift.Int32 = Swift.Int32()

  /// Max disk IO rate, in kilobytes per second.
  public var diskIoRateMaxKbps: Swift.Int64 = Swift.Int64()

  /// Average disk IO rate, in kilobytes per second.
  public var diskIoRateAverageKbps: Swift.Int64 = Swift.Int64()

  /// Max network throughput (combined transmit-rates and receive-rates), in
  /// kilobytes per second.
  public var networkThroughputMaxKbps: Swift.Int64 = Swift.Int64()

  /// Average network throughput (combined transmit-rates and receive-rates), in
  /// kilobytes per second.
  public var networkThroughputAverageKbps: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `VmUtilizationMetrics`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VmUtilizationMetrics().with { $0.cpuMaxPercent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.VmUtilizationMetrics"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
