// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Utilization information of a single VM.
public struct VmUtilizationInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The VM's ID in the source.
  public var vmId: Swift.String = Swift.String()

  /// Utilization metrics for this VM.
  public var utilization: VmUtilizationMetrics? = nil

  public var vmDetails: OneOf_VmDetails? = nil

  /// Initialize a new instance of `VmUtilizationInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VmUtilizationInfo().with { $0.vmwareVmDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case vmwareVmDetails = "vmwareVmDetails"
    case vmId = "vmId"
    case utilization = "utilization"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.vmId = try container.decode(Swift.String.self, forKey: .vmId)
    self.utilization = try container.decodeIfPresent(
      VmUtilizationMetrics.self, forKey: .utilization)

    var vmDetails: OneOf_VmDetails? = nil
    let vmDetailsCheckAndSet = {
      if vmDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'vmDetails'"))
      }
      vmDetails = $0
    }
    if let vmwareVmDetails = try container.decodeIfPresent(
      VmwareVmDetails?.self, forKey: .vmwareVmDetails)
    {
      try vmDetailsCheckAndSet(.vmwareVmDetails(vmwareVmDetails))
    }
    self.vmDetails = vmDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.vmId, forKey: .vmId)
    try container.encode(self.utilization, forKey: .utilization)

    if let choice = self.vmDetails {
      switch choice {
      case .vmwareVmDetails(let value):
        try container.encode(value, forKey: .vmwareVmDetails)
      }
    }
  }

  public enum OneOf_VmDetails: Codable, Equatable, Sendable {
    /// The description of the VM in a Source of type Vmware.
    indirect case vmwareVmDetails(VmwareVmDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.VmUtilizationInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
