// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// VmwareVmDetails describes a VM in vCenter.
public struct VmwareVmDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The VM's id in the source (note that this is not the MigratingVm's id).
  /// This is the moref id of the VM.
  public var vmId: Swift.String = Swift.String()

  /// The id of the vCenter's datacenter this VM is contained in.
  public var datacenterId: Swift.String = Swift.String()

  /// The descriptive name of the vCenter's datacenter this VM is contained in.
  public var datacenterDescription: Swift.String = Swift.String()

  /// The unique identifier of the VM in vCenter.
  public var uuid: Swift.String = Swift.String()

  /// The display name of the VM. Note that this is not necessarily unique.
  public var displayName: Swift.String = Swift.String()

  /// The power state of the VM at the moment list was taken.
  public var powerState: VmwareVmDetails.PowerState = VmwareVmDetails.PowerState()

  /// The number of cpus in the VM.
  public var cpuCount: Swift.Int32 = Swift.Int32()

  /// The size of the memory of the VM in MB.
  public var memoryMb: Swift.Int32 = Swift.Int32()

  /// The number of disks the VM has.
  public var diskCount: Swift.Int32 = Swift.Int32()

  /// The total size of the storage allocated to the VM in MB.
  public var committedStorageMb: Swift.Int64 = Swift.Int64()

  /// The VM's OS. See for example
  /// https://vdc-repo.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html
  /// for types of strings this might hold.
  public var guestDescription: Swift.String = Swift.String()

  /// Output only. The VM Boot Option.
  public var bootOption: VmwareVmDetails.BootOption = VmwareVmDetails.BootOption()

  /// Output only. The CPU architecture.
  public var architecture: VmwareVmDetails.VmArchitecture = VmwareVmDetails.VmArchitecture()

  /// Initialize a new instance of `VmwareVmDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VmwareVmDetails().with { $0.vmId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible values for the power state of the VM.
  public enum PowerState: Codable, Equatable, Sendable {
    /// Power state is not specified.
    case unspecified
    /// The VM is turned ON.
    case on
    /// The VM is turned OFF.
    case off
    /// The VM is suspended. This is similar to hibernation or sleep mode.
    case suspended
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .on: return 1
      case .off: return 2
      case .suspended: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "POWER_STATE_UNSPECIFIED"
      case .on: return "ON"
      case .off: return "OFF"
      case .suspended: return "SUSPENDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PowerState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "POWER_STATE_UNSPECIFIED": self = .unspecified
      case "ON": self = .on
      case "OFF": self = .off
      case "SUSPENDED": self = .suspended
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PowerState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .on
      case 2: self = .off
      case 3: self = .suspended
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .on: return try container.encode(1)
      case .off: return try container.encode(2)
      case .suspended: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible values for vm boot option.
  public enum BootOption: Codable, Equatable, Sendable {
    /// The boot option is unknown.
    case unspecified
    /// The boot option is EFI.
    case efi
    /// The boot option is BIOS.
    case bios
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .efi: return 1
      case .bios: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BOOT_OPTION_UNSPECIFIED"
      case .efi: return "EFI"
      case .bios: return "BIOS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BootOption/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BOOT_OPTION_UNSPECIFIED": self = .unspecified
      case "EFI": self = .efi
      case "BIOS": self = .bios
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BootOption/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .efi
      case 2: self = .bios
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .efi: return try container.encode(1)
      case .bios: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible values for the VM architecture.
  public enum VmArchitecture: Codable, Equatable, Sendable {
    /// The architecture is unknown.
    case unspecified
    /// The architecture is one of the x86 architectures.
    case x86Family
    /// The architecture is ARM64.
    case arm64
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .x86Family: return 1
      case .arm64: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VM_ARCHITECTURE_UNSPECIFIED"
      case .x86Family: return "VM_ARCHITECTURE_X86_FAMILY"
      case .arm64: return "VM_ARCHITECTURE_ARM64"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VmArchitecture/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VM_ARCHITECTURE_UNSPECIFIED": self = .unspecified
      case "VM_ARCHITECTURE_X86_FAMILY": self = .x86Family
      case "VM_ARCHITECTURE_ARM64": self = .arm64
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VmArchitecture/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .x86Family
      case 2: self = .arm64
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .x86Family: return try container.encode(1)
      case .arm64: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vmmigration.v1.VmwareVmDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
